### ISSUE TITLE
网易云音乐播放问题

### ISSUE THREAD

**Issue by uouo20** [xb2016/Kratos#2]
后台输入`[music]30953009[/music]`
前台有页面但是无法播放！
希望大佬解决
[实例页面](https://www.xtaolink.cn/8.html)

**Comment by xb2016** [comment]
我访问http://music.163.com/#/song?id=30953009 发现也无法播放。综上，网易云的锅，不应该找我。

**Comment by xb2016** [comment]
不对，我再看看

**Comment by freejishu** [comment]
http://music.163.com/#/song?id=30953009
山东联通测试可以播放。。。
你确定么。。。

**Comment by uouo20** [comment]
这边四川联通可以播放
http://music.163.com/#/song?id=30953009
插入博客后没办法QWQ @xb2016

**Comment by xb2016** [comment]
我知道了 这歌有版权保护，我这个主题是不能绕过这个东西获取外链的。

**Comment by freejishu** [comment]
确认了一下 id=30953009 See You Again (feat. Charlie Puth) 系版权保护 使用“生成外链服务器”接口无法正确解析链接 （网页生成会提示“由于版权保护，无法生成外链。”）
建议换一首歌或者自行上传mp3在做引用

**Comment by freejishu** [comment]
@xb2016 你为什么总是比我快一步

**Comment by uouo20** [comment]
感谢两位大佬，可是怎么下mp3呢=、=

**Comment by freejishu** [comment]
@uouo20 F12捕获一下或者用网易云客户端

**Comment by xb2016** [comment]
喵

**Comment by uouo20** [comment]
感谢QWQ

**Comment by uouo20** [comment]
话说怎么看有没有版权保护呢=、=

**Comment by freejishu** [comment]
网易云音乐网页版 唱片似的专辑图片下方有个“生成外链播放器”，如果没有提示“由于版权保护，无法生成外链。”那博客就可以直接链接，否则不能。

**Comment by uouo20** [comment]
感谢 @freejishu @xb2016
