### ISSUE TITLE
#2b77348 最新版本顶部菜单不显示

### ISSUE THREAD

**Issue by pkuplus** [xb2016/Kratos#3]
1、顶部菜单不显示，试了几次都这样，请查看。
2、`.color-logo{float:left;width:20%}` 如果是纯文字不含图片的话，`width:20%` 会限制文字长度。

**Comment by xb2016** [comment]
站点链接发来看看

**Comment by pkuplus** [comment]
还在本地调试。我看你 commit 中说是昨天用了纯 css 来重写菜单，你本地调试 OK 吗？

我等会儿用两天前的版本看看是否是版本问题。

**Comment by xb2016** [comment]
我的测试站和主站均没有发现问题

**Comment by pkuplus** [comment]
好的👌，我再确认下。谢谢回复。

**Comment by pkuplus** [comment]
@xb2016 删了数据库，重新下载最新主题，设置后可以了。

ps: 很好的主题修改，已 Donate ！

**Comment by xb2016** [comment]
谢谢

**Comment by pkuplus** [comment]
@xb2016 对了，我后来重做是把 `wp-content/themes/` 下的 主题名称改成 `Krato` 才行的。之前是 `Krato-master`，您可以在主题使用中提一下。

**Comment by xb2016** [comment]
理论上命名不影响使用的，我主站文件夹名字是`Kratos_fczbl`，未发现问题

**Comment by pkuplus** [comment]
@xb2016 嗯。有些主题是会明确说要改名字，比如去掉 `-master` 等。您这个主题我后来又加上了 `-master`，顶部菜单就消失了，试了几次都这样。

**Comment by pkuplus** [comment]
@xb2016 知道了。是去掉 `.color-logo{float:left;width:20%}` 中的 `width:20%` 造成的，应该与 themes 中的主题命名无关。

**Comment by xb2016** [comment]
![default](https://user-images.githubusercontent.com/31783875/36190334-8a63da86-1192-11e8-94a8-dbcfc41ee20e.png)
我这里测试通过，并没有消失，重命名后请尝试对主题和菜单进行重新设置。

**Comment by xb2016** [comment]
改宽度你可以把20% 80%换成 40% 60%就行了

**Comment by seuplus** [comment]
@xb2016 谢谢。`主题设置 >> 模版页面` 中的 `点赞`、`分享` 按钮点了取消，但似乎无效，文章中仍旧存在，你那边可以吗？

**Comment by xb2016** [comment]
@seuplus 文章的设置是在`内容页面`设置的，页面的设置才是`模板页面`。其中点赞功能无法通过主题设置删除。

**Comment by pkuplus** [comment]
@xb2016 OK，那我去 `single.php` 手动注释掉它们。
