### ISSUE TITLE
是否可以增加一个“页面归档”模版

### ISSUE THREAD

**Issue by pkuplus** [xb2016/Kratos#4]
一般的主题都会有一个 `页面归档` 模版，这样便于访客快速查找感兴趣的文章。 谷歌了下 Kratos 主题好像还没有谁的博客做了 `页面归档`，有空是否可以增加一个“页面归档”模版？

**Comment by xb2016** [comment]
框架已基本完成，外观与功能调整等有电脑了再做。[https://www.fczbl.vip/archives.html](https://www.fczbl.vip/archives.html)

**Comment by pkuplus** [comment]
@xb2016 [Advice] 建议 `js/kratos.js`  中的 `console.clear();` 默认关闭，这样方便打开命令台查看错误提示。

**Comment by xb2016** [comment]
@pkuplus 1.文章归档模板已完成 2.控制台清除命令有需要的可自行删除，我这里不删
