### ISSUE TITLE
4.1.0并未修复 图片说明文字不居中 问题

### ISSUE THREAD

**Issue by wkingnet** [xb2016/Kratos#471]
经测试，更新到4.1.0版本后，不论旧文章还是新建文章，图片和图片说明文字对齐方式都是“无”，不是默认居中对齐

另外，页脚版权信息，作者的网站打不开？

**Comment by seatonjiang** [comment]
是用的经典编辑器吗？

**Comment by wkingnet** [comment]
> 是用的经典编辑器吗？

不是，是谷腾堡

**Comment by seatonjiang** [comment]
修复了这个问题，现在的处理方式跟官方的 Twenty Twenty-Two 一致了，下个版本更新即可。

![image](https://user-images.githubusercontent.com/57834639/154846935-a44f99db-9e0e-44fa-ad91-6d6e2a1a531d.png)
![image](https://user-images.githubusercontent.com/57834639/154846944-a915ffb9-dd8d-405a-ab33-dc97568ca732.png)

**Comment by wkingnet** [comment]
不知道为什么，我这里现在图片说明文字居中了，但图片仍然无法居中，请问是哪里出了问题？是我要手动选上“图片居中对齐”吗

http://wkings.blog/archives/293

![QQ截图20220221113357](https://user-images.githubusercontent.com/57652989/154885094-13ff0b05-6208-41c8-8333-c6aa6932c47d.png)
![QQ截图20220221113412](https://user-images.githubusercontent.com/57652989/154885098-9df3b3ad-a2d9-4e5d-b20d-044eb374189d.png)

**Comment by seatonjiang** [comment]
@wkingnet  你要手动选择图片居中，目前的样式规则跟官方的 Twenty Twenty-Two 一致

**Comment by wkingnet** [comment]
> 

我建议考虑一下默认图片居中？

**Comment by wkingnet** [comment]
> @wkingnet 你要手动选择图片居中，目前的样式规则跟官方的 Twenty Twenty-Two 一致

我建议考虑一下默认图片居中？
