### ISSUE TITLE
4.1.0中顶部配置等一些相关建议

### ISSUE THREAD

**Issue by sc8cn** [xb2016/Kratos#472]
1、4.1.0版在顶部配置》颜色导航中，只能更改背景色，如果背景色改为白色，导航文字无法设置变更字体颜色，导航内容就看不见了。
2、文章及文章列表页，希望能增加“作者”“热度”“评论数”等相关内容的启用或禁用设置，以便更灵活的应用。

**Comment by n0099** [comment]
1.建议自己改css
2.建议自己在child theme里改https://github.com/seatonjiang/kratos/blob/main/pages/page-content.php

**Comment by sc8cn** [comment]
您好，来信已到达目的地，我的主人将择日阅读，谢谢！

**Comment by seatonjiang** [comment]
收到，这里改一下可以自定义标题和导航文字的颜色。

**Comment by sc8cn** [comment]
您好，来信已到达目的地，我的主人将择日阅读，谢谢！

**Comment by seatonjiang** [comment]
文章标签的自定义功能已经加上了，下个版本更新即可。

![image](https://user-images.githubusercontent.com/57834639/154847881-55782ad9-94cc-48a9-b6d9-e902390a4fc7.png)
![image](https://user-images.githubusercontent.com/57834639/154847906-7b073e93-313e-44ff-ad39-7fd07e5ba398.png)

**Comment by seatonjiang** [comment]
标题栏自定义颜色的功能已经加上了，下个版本更新即可。

![image](https://user-images.githubusercontent.com/57834639/154849087-e4697bbd-167b-47ee-a22a-f2668f8df333.png)

![image](https://user-images.githubusercontent.com/57834639/154849101-4047fd86-fffa-47a1-9ef4-53e56adf17cd.png)
