### ISSUE TITLE
文章页面目录工具宽度调整

### ISSUE THREAD

**Issue by li-zheng-hao** [xb2016/Kratos#473]
![image](https://user-images.githubusercontent.com/22129824/152340577-9e1d35ac-8ed7-441c-b3fb-65ed56a1e8b4.png)

感觉文章界面的目录有点过宽了，有什么地方可以调整一下吗？

**Comment by seatonjiang** [comment]
添加一点小工具试试？

**Comment by li-zheng-hao** [comment]
算了，就这样吧....懒得整了
