### ISSUE TITLE
请问本模板有无做对英语的翻译？

### ISSUE THREAD

**Issue by Vinceli2401** [xb2016/Kratos#474]
劳烦问一下现在模板有没有做英语的本地化，如果没有的话我就自己搞个po文件出来（

**Comment by seatonjiang** [comment]
https://crowdin.com/project/kratos 在这里提交即可。

**Comment by Vinceli2401** [comment]
好哦 我可以在本地翻译完以后将po/mo文件直接上传到这上面吗？（不使用在线编辑器

**Comment by seatonjiang** [comment]
都可以

**Comment by VancyLee** [comment]
好了 英语的本地化翻译已经提交了

**Comment by Vinceli2401** [comment]
好了 英语的本地化翻译已经提交了

**Comment by seatonjiang** [comment]
翻译已经拉取了，等下次版本更新进行推送。
