### ISSUE TITLE
主题是否能集成，wp媒体库上传图片，优化为只见当前文章图片

### ISSUE THREAD

**Issue by yaociyuan** [xb2016/Kratos#476]
使用 WordPress 的朋友应该都清楚，特别是喜欢图文并茂的网站，肯定离不开的就是 WordPress 文章编辑页面的“添加媒体”按钮，每次点击就能弹出一个插入多媒体的界面，然后页面默认就会列举加载所有最近的媒体库上传的文件，从而文件过多过大的请求下载，就可能造成页面的卡顿或假死，同时也会造成服务器带宽资源的浪费，严重影响网站内容的编辑和效率。

代码部分

//WordPress “添加媒体”文件时只显示上传到当前文章的附件
//add_action( 'wp_footer', 'fanly_mediapanel_lock_uploaded' );//让前台编辑器也生效
add_action( 'admin_footer-post-new.php', 'fanly_mediapanel_lock_uploaded' );
add_action( 'admin_footer-post.php', 'fanly_mediapanel_lock_uploaded' );
function fanly_mediapanel_lock_uploaded() {
	echo '<script type="text/javascript">var $i=0;jQuery(document).on("DOMNodeInserted", function(){if(jQuery("#media-attachment-filters").length>0&&$i==0){jQuery(\'select.attachment-filters [value="uploaded"]\').attr(\'selected\',true).parent().trigger(\'change\');$i++;}});</script>';
}

**Comment by seatonjiang** [comment]
收到，我这里看一下。

**Comment by seatonjiang** [comment]
功能已经添加了，下个版本更新即可。

![image](https://user-images.githubusercontent.com/57834639/154849797-5ef419ce-b557-4eab-b8f8-6a9d6be12d37.png)
![image](https://user-images.githubusercontent.com/57834639/154849804-650a1b45-d7c7-41d0-912c-a6d1c3e7315e.png)
