### ISSUE TITLE
长文章中标题太长会存在内容全部看完了，但是标题还没有显示完，详见截图

### ISSUE THREAD

**Issue by huamux-dev** [xb2016/Kratos#477]
![image](https://user-images.githubusercontent.com/58031091/154780958-b597bf72-f60c-4645-9a56-7e632081d1b3.png)

**Comment by seatonjiang** [comment]
hi@seatonjiang.com 麻烦提供一下这篇文章的地址，我看一下怎么优化。

**Comment by seatonjiang** [comment]
添加了一个滚动条，默认展示 350px 的尺寸，等下个版本推送即可。

![image](https://user-images.githubusercontent.com/57834639/154944348-ef1e84b6-9c83-4018-af14-1e8d44fe0483.png)

**Comment by soleilxxx** [comment]
你好 我在你的一个网址上付费下载了一些视频 但是下载后发现需要解压密码 能告知吗

**Comment by n0099** [comment]
> 你好 我在你的一个网址上付费下载了一些视频 但是下载后发现需要解压密码 能告知吗

@dvomu

**Comment by huamux-dev** [comment]
> > 你好 我在你的一个网址上付费下载了一些视频 但是下载后发现需要解压密码 能告知吗
> 
> @dvomu

我网站上没有付费视频哦

**Comment by huamux-dev** [comment]
> 你好 我在你的一个网址上付费下载了一些视频 但是下载后发现需要解压密码 能告知吗

我网站上没有付费视频哦

**Comment by huamux-dev** [comment]
https://www.dvomu.com/architect/124.html
