### ISSUE TITLE
这个站长简介上面的图片如何更改

### ISSUE THREAD

**Issue by JeMSky** [xb2016/Kratos#481]
这个站长简介上面的图片如何更改
![(L21XU0U906A2CIR57{O9`B](https://user-images.githubusercontent.com/75385172/155690504-77f7ef22-8813-4340-807b-55f9eb11c2f7.png)

**Comment by n0099** [comment]
主题设置header image

**Comment by JeMSky** [comment]
主题设置的哪个选项里面的？

**Comment by mohanfeng3** [comment]
为啥我没找到这个 header image
