### ISSUE TITLE
文章显示图片如何更改

### ISSUE THREAD

**Issue by JeMSky** [xb2016/Kratos#482]
文章显示图片如何更
![H}U@{G3U003KH7W~F`SU SX](https://user-images.githubusercontent.com/75385172/155691491-34f746ce-7295-43f3-99e5-aa8bb650972b.png)
改

**Comment by n0099** [comment]
post的featured image

**Comment by JeMSky** [comment]
呃呃呃呃，这个具体在哪，没找到。。。。。。？谢谢帮助！

**Comment by n0099** [comment]
文章的特色图片

**Comment by mohanfeng3** [comment]
可不可以设置，当文章没有图片的时候，默认特色图能否随机，现在是固定只有一个，可不可以有10个，然后随机一个。这样页面不会看着很单调

**Comment by n0099** [comment]
我自己在子主题里是这样实现将文章里第一张图片显示为默认图片的：
```php
// https://github.com/vtrois/kratos/blob/94d8289820bd94726fd4b3bdf58bf2e6d8fa8121/inc/theme-article.php#L108
function child_theme_post_thumbnail()
{
    global $contentFilter;
    $img_url = wp_get_attachment_image_src(get_post_thumbnail_id(), 'kratos-thumbnail');
    if (is_array($img_url)) {
        $img_url = $img_url[0];
    }
    if (has_post_thumbnail()) {
        $echo = '<img src="' . $img_url . '" />';
    } else {
        global $post;
        $content = $post->post_content;
        $img_preg = "/<img (.*?)src=\"(.+?)\".*?>/";
        preg_match($img_preg, $content, $img_src);
        $img_count = count($img_src) - 1;
        if (isset($img_src[$img_count])) {
            $img_val = $img_src[$img_count];
        }
        if (!empty($img_val)) {
            $echo = '<img src="' . $img_val . '" />';
        } else {
            if (!kratos_option('g_postthumbnail')) {
                $img = ASSET_PATH . '/assets/img/default.jpg';
            } else {
                $img = kratos_option('g_postthumbnail', ASSET_PATH . '/assets/img/default.jpg');
            }
            $echo = '<img src="' . $img . '" />';
        }
    }
    echo str_replace('<img src', '<img class="article-featured-img" src', $contentFilter($echo));
}
```
并修改文件https://github.com/seatonjiang/kratos/blob/8336803e0f660d275dc2873f950051337614c773/pages/page-content.php#L21-L25
为：
```html
    <div class="a-thumb">
        <a href="<?php the_permalink(); ?>">
            <?php child_theme_post_thumbnail(); ?>
        </a>
    </div>
```

**Comment by mohanfeng3** [comment]
谢谢分享，文章类图片第一张这个学会了。
如果是文章没有图片呢，主题里面可以设置一张，我想实现的是，当文章没有图片的时候，随机显示自己设置的10张图片里面的其中一张

**Comment by herper** [comment]
> 谢谢分享，文章类图片第一张这个学会了。 如果是文章没有图片呢，主题里面可以设置一张，我想实现的是，当文章没有图片的时候，随机显示自己设置的10张图片里面的其中一张

文章里没有图片那就抓取不了，你自己设置特色图片，或是直接把主题里这张图替换成你想要的图片
图片位置：https://github.com/seatonjiang/kratos/blob/8336803e0f660d275dc2873f950051337614c773/assets/img/default.jpg

**Comment by n0099** [comment]
> > 谢谢分享，文章类图片第一张这个学会了。 如果是文章没有图片呢，主题里面可以设置一张，我想实现的是，当文章没有图片的时候，随机显示自己设置的10张图片里面的其中一张
> 
> 文章里没有图片那就抓取不了，你自己设置特色图片，或是直接把主题里这张图替换成你想要的图片 图片位置：https://github.com/seatonjiang/kratos/blob/8336803e0f660d275dc2873f950051337614c773/assets/img/default.jpg

他要的是随机特色图片，我记得有些二次元wp主题有这功能
