### ISSUE TITLE
工信部备案号跳转链接错误

### ISSUE THREAD

**Issue by yujitai** [xb2016/Kratos#484]
在页脚设置页面，可以填写工信部备案号，然后这个主题会自动跳转到工信部备案网站链接，但是跳转的链接是错误的。

正确的工信部链接：https://beian.miit.gov.cn/
主题自动跳转的错误的链接：https://www.beian.miit.gov.cn

我是用的腾讯云的ecs，他们会检查这个备案，必须要展示，而且链接要对，否则会取消备案，注销网站，影响蛮大。
我现在是换了主题，希望大佬能修复这个问题，我到时候会再换回来。

**Comment by seatonjiang** [comment]
主题默认的工信部网址没有问题

https://github.com/seatonjiang/kratos/blob/804bafd6908c1c6d0d02fe84c0db83d045620ac3/footer.php#L49-L51

**Comment by seatonjiang** [comment]
你检测一下主题版本是不是老版本，最新的版本是 4.1.1

**Comment by n0099** [comment]
3.0中是www.beian.miit.gov.cn
https://github.com/seatonjiang/kratos/issues/276

https://github.com/seatonjiang/kratos/blame/d4e15b6fa6433a094254f545fabd3db87c760c0f/footer.php#L49

**Comment by herper** [comment]
> 

4.0以前的版本得你自己更新一下

**Comment by yujitai** [comment]
> 

好的，应该是版本太老了，我更新下。多谢
