### ISSUE TITLE
建议：文章页可否添加 猜你喜欢

### ISSUE THREAD

**Issue by mohanfeng3** [xb2016/Kratos#486]
手机版 文章页，阅读文章后的下面能否添加  猜你喜欢/相关推荐   这样能减少跳出率，对SEO会更好一些

**Comment by n0099** [comment]
有一堆这样的插件
https://wordpress.org/plugins/yet-another-related-posts-plugin/

**Comment by seatonjiang** [comment]
赞同使用插件的方式实现，插件控制起来比主题添加会更专业，并且更能满足需求。
