### ISSUE TITLE
页脚显示过高该如何自由调整

### ISSUE THREAD

**Issue by mairoot** [xb2016/Kratos#487]
个人因感觉页脚过于高占用过多空白地方，影响浏览空间，想调小高度。
因为css使用了CDN的原因，在本地修改页脚高度没有生效，是否有其他方式可以调整?
![8](https://user-images.githubusercontent.com/23660039/159311268-b7ad3b7e-2e1a-403e-95a8-e8e0b253c707.png)
![9](https://user-images.githubusercontent.com/23660039/159311335-c6167f2e-5ba0-419c-9116-084bd4359212.png)

**Comment by n0099** [comment]
在子主题的style.css里无脑!important

**Comment by seatonjiang** [comment]
> 在子主题的style.css里无脑!important

赞同这个做法
