### ISSUE TITLE
主体设置菜单打不开

### ISSUE THREAD

**Issue by ohaowyl** [xb2016/Kratos#491]
在侧面菜单点击“主题设置”后，在浏览器右侧窗口会列出一个清单，列出来所有的配置菜单，但是点击任何一个菜单，都没有反应，如下面的截图所示：

![image](https://user-images.githubusercontent.com/103031886/161720139-8c499c03-3e41-43ea-9b17-68c11757df7d.png)

我的环境信息：
1，Chrome, 版本 100.0.4896.60（正式版本） （64 位）, 
2，Wordpress, 5.9.2
3, Kratos, 4.1.2

**Comment by seatonjiang** [comment]
F12 看一下，CSS 和 JS 资源是否正确加载了

**Comment by seatonjiang** [comment]
暂时先关闭这个问题，有问题随时打开反馈。

**Comment by puffinjiang** [comment]
出现了相同的问题：
环境信息：
1. chrome 134.0.6998.37
2. WordPress 6.7.2
3. Kratos 4.3.2

通过 F12 看到以下三个文件加载时出现 404

```
https://xxx.com/wp-content/themes/kratos-4.3.2/bitnami/wordpress/wp-content/themes/kratos-4.3.2/inc/codestar-framework/assets/css/style.min.css?ver=2.2.4

https://xxx.com/wp-content/themes/kratos-4.3.2/bitnami/wordpress/wp-content/themes/kratos-4.3.2/inc/codestar-framework/assets/js/plugins.min.js?ver=2.2.4

https://xxx.com/wp-content/themes/kratos-4.3.2/bitnami/wordpress/wp-content/themes/kratos-4.3.2/inc/codestar-framework/assets/js/main.min.js?ver=2.2.4
```
