### ISSUE TITLE
谷腾堡编辑器缺失排版CSS

### ISSUE THREAD

**Issue by wkingnet** [xb2016/Kratos#492]
我开始以为是哪个插件的问题，刚发现原来是kratos的问题。

简单的说就是使用kratos主题时，编辑文章、页面使用谷腾堡编辑器，每个块都是左对齐，和左边的菜单栏紧挨着，这样输入文字看起来都很别扭。

其他主题和默认主题都有优化。如图：

![11](https://user-images.githubusercontent.com/57652989/162683073-80deaa26-c342-42a0-aef3-8abf35fd51d1.png)

![3](https://user-images.githubusercontent.com/57652989/162683097-92175f1f-59cb-46d9-9055-fc1daf513cf1.png)

![22](https://user-images.githubusercontent.com/57652989/162683105-0d308d2f-61fa-4942-be04-40156fd65c0c.png)

**Comment by seatonjiang** [comment]
这个是怎么调出来左侧的边栏的？我这里打开写文章就是全屏的编辑器

**Comment by n0099** [comment]
> 这个是怎么调出来左侧的边栏的？我这里打开写文章就是全屏的编辑器

右上角三个点菜单里关闭全屏或者按ctrl+shift+alt+f

**Comment by wkingnet** [comment]
> 这个是怎么调出来左侧的边栏的？我这里打开写文章就是全屏的编辑器

切换就是按楼上所说。如果是全屏的话，那就直接顶到屏幕边缘了，更别扭

**Comment by seatonjiang** [comment]
我这里没问题，你那看看debug，是不是有什么没有加载的CSS
![image](https://user-images.githubusercontent.com/57834639/163509658-85dfc33d-bf0e-4c56-9620-89b96ca9ee57.png)

**Comment by wkingnet** [comment]
我又试了一下，好像是浏览器的问题？我用百分浏览器【版本 4.3.9.248（正式版本） （64 位） (Portable) (Chromium 86.0.4240.198)】就有问题，换了Firefox【98.0 (64 位)】和edge【版本 100.0.1185.39】就是好的。

即使我禁用了所有插件和浏览器扩展也没用。

我也不知道怎么办了，既然不是kratos的问题就好

**Comment by seatonjiang** [comment]
更新浏览器试一下？

**Comment by wkingnet** [comment]
我刚开虚拟机装了一个纯净的windows和百分浏览器，仍然是这样，确定是浏览器的问题。可能内核太低了？我记得kratos前几个月的版本还是正常的，忘了从哪个版本开始就这样了。

百分浏览器已经是最新版了，更新的慢，但功能对我挺合适的，不想换浏览器了。这个也不是什么大问题，不影响使用，大不了我用其他浏览器写文章哈哈

**Comment by SiloRanger** [comment]
同楼主, 也是百分浏览器, 几个月前更新后就这样了. 内核太老了.

**Comment by nilopmas** [comment]
请问楼主是如何切换为Gutengberg编辑器的？我用其他主题的时候可以用Gutenberg编辑器，但使用Kratos的时候取而代之的是默认编辑器：
![image](https://user-images.githubusercontent.com/40747250/165491429-eeff3da8-7212-4c65-ab25-1a2b0c3dcda8.png)
Setting->Writing也没有出现Default Editor的选项：
![image](https://user-images.githubusercontent.com/40747250/165491734-596637c4-5550-4b34-bfe8-f737d1b29afe.png)

**Comment by nilopmas** [comment]
> 请问楼主是如何切换为Gutengberg编辑器的？我用其他主题的时候可以用Gutenberg编辑器，但使用Kratos的时候取而代之的是默认编辑器： ![image](https://user-images.githubusercontent.com/40747250/165491429-eeff3da8-7212-4c65-ab25-1a2b0c3dcda8.png) Setting->Writing也没有出现Default Editor的选项： ![image](https://user-images.githubusercontent.com/40747250/165491734-596637c4-5550-4b34-bfe8-f737d1b29afe.png)

Kratos版本4.1.2，WordPress版本5.9.3

**Comment by wkingnet** [comment]
> > 请问楼主是如何切换为Gutengberg编辑器的？我用其他主题的时候可以用Gutenberg编辑器，但使用Kratos的时候取而代之的是默认编辑器： ![image](https://user-images.githubusercontent.com/40747250/165491429-eeff3da8-7212-4c65-ab25-1a2b0c3dcda8.png) Setting->Writing也没有出现Default Editor的选项： ![image](https://user-images.githubusercontent.com/40747250/165491734-596637c4-5550-4b34-bfe8-f737d1b29afe.png)
> 
> Kratos版本4.1.2，WordPress版本5.9.3

kratos默认启用的经典编辑器，在后台主题设置(也就是kratos设置)-全站配置-功能配置里，有个谷腾堡编辑器开关

**Comment by nilopmas** [comment]
> > > 请问楼主是如何切换为Gutengberg编辑器的？我用其他主题的时候可以用Gutenberg编辑器，但使用Kratos的时候取而代之的是默认编辑器： ![image](https://user-images.githubusercontent.com/40747250/165491429-eeff3da8-7212-4c65-ab25-1a2b0c3dcda8.png) Setting->Writing也没有出现Default Editor的选项： ![image](https://user-images.githubusercontent.com/40747250/165491734-596637c4-5550-4b34-bfe8-f737d1b29afe.png)
> > 
> > 
> > Kratos版本4.1.2，WordPress版本5.9.3
> 
> kratos默认启用的经典编辑器，在后台主题设置(也就是kratos设置)-全站配置-功能配置里，有个谷腾堡编辑器开关

感谢回答，刚刚已经成功加载出来。请问切换为古腾堡编辑器后就可以搭配其他插件使用吗？

**Comment by wkingnet** [comment]
> > > > 请问楼主是如何切换为Gutengberg编辑器的？我用其他主题的时候可以用Gutenberg编辑器，但使用Kratos的时候取而代之的是默认编辑器： ![image](https://user-images.githubusercontent.com/40747250/165491429-eeff3da8-7212-4c65-ab25-1a2b0c3dcda8.png) Setting->Writing也没有出现Default Editor的选项： ![image](https://user-images.githubusercontent.com/40747250/165491734-596637c4-5550-4b34-bfe8-f737d1b29afe.png)
> > > 
> > > 
> > > Kratos版本4.1.2，WordPress版本5.9.3
> > 
> > 
> > kratos默认启用的经典编辑器，在后台主题设置(也就是kratos设置)-全站配置-功能配置里，有个谷腾堡编辑器开关
> 
> 感谢回答，刚刚已经成功加载出来。请问切换为古腾堡编辑器后就可以搭配其他插件使用吗？

那看你有什么插件？大部分插件其实和编辑器没多大关系。关系比较密切的我觉得就是代码高亮插件。现在插件也都兼容谷腾堡编辑器。

而且就我使用感受来看，谷腾堡编辑器适合大段落的文字书写，简单配几个图。经典编辑器适合复杂的文章，比如文章中代码、图片、表格多。

**Comment by n0099** [comment]
建议梦回 https://wordpress.org/plugins/tinymce-advanced/

**Comment by nilopmas** [comment]
> 

了解，一开始我也不是很习惯古腾堡编辑器，但习惯后觉得对网站预览有更直观的表现。

**Comment by seatonjiang** [comment]
问题修复了，升级4.1.3即可
