### ISSUE TITLE
主机php版本730，后台启用了别的主题之后，再切回 kratos提示当前版本不兼容，无法启用本主题了。

### ISSUE THREAD

**Issue by ivkeji** [xb2016/Kratos#493]
https://p.qlogo.cn/hy_personal/3e28f14aa0516842f278f8097f0160f6c1743fef6165e3c39507b0f0d7f8d65b/0.jpg
启用按钮无法点击。

**Comment by n0099** [comment]
建议立即更新php至8.1
如果您实在无法更新那就把style.css的这一行
https://github.com/seatonjiang/kratos/blob/0c7bd0a42efc15b0e53dc4ca5292f34a4a752f98/style.css#L6
改成7.3

**Comment by ivkeji** [comment]
谢谢你。主机商php版本最高只设置到7.3。
使用第二种方法。已成功启用主题
