### ISSUE TITLE
个人信息栏不显示

### ISSUE THREAD

**Issue by Calderic** [xb2016/Kratos#495]
![image](https://user-images.githubusercontent.com/63099604/165094010-1c48e937-1c5e-4f3f-a543-e367ad4c53c3.png)
缺少侧边栏展示

**Comment by n0099** [comment]
主题设置你改成双栏布局

**Comment by Calderic** [comment]
![image](https://user-images.githubusercontent.com/63099604/165131842-ae7540f9-fd00-4814-8cba-5453b000e26a.png)
就是这样设置的

**Comment by citratecycle** [comment]
@gudaonanfeng 需要在外观->小工具那里，把浮动小工具添加到侧边栏

**Comment by Calderic** [comment]
解决了感谢
