### ISSUE TITLE
【改进】修复个人简介中头像分辨率过低的问题

### ISSUE THREAD

**Issue by citratecycle** [xb2016/Kratos#498]
Wordpress的`get_avatar_url()` API默认提供的是96x96的头像，分辨率过低，可以通过将`inc/theme-widgets.php`第301行的函数调用改为
```php
$avatar = get_avatar_url('1', ['size' => '300']);
```
解决。这样可以得到一张分辨率为300x300的头像。

也可以将这个参数放入选项菜单，由用户自行决定。

**Comment by n0099** [comment]
#499

**Comment by seatonjiang** [comment]
感谢反馈，等下版更新即可。
