### ISSUE TITLE
有没有可能支持一下全页面单栏？

### ISSUE THREAD

**Issue by citratecycle** [xb2016/Kratos#500]
现在好像只有一个文章页（posts）单双栏切换功能，能不能允许主页（feeds）和页面（pages）也可以切换成单栏显示？

**Comment by iamlvtu** [comment]
后面增加一个开关，然后写CSS...

**Comment by seatonjiang** [comment]
添加了一个单栏的页面样式，可以在页面中选择这个模板，默认模版就是有分栏的，新版本进行推送。

<img width="632" alt="image" src="https://user-images.githubusercontent.com/57834639/204135934-819e987a-29c3-49f6-8c33-0450672680ed.png">

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/57834639/204135942-8394d80f-e783-49e5-a1fd-53bf895f3226.png">
