### ISSUE TITLE
2个建议：1 英文跨行会截断，2 代码框能否美化下

### ISSUE THREAD

**Issue by qglian** [xb2016/Kratos#501]
1，英文跨行会截断。特别是标题，如下截图
![image](https://user-images.githubusercontent.com/65819267/166403094-008b9158-1327-4375-8aae-00f6f67c4515.png)
演示网址 http://nejm.net/paper/2219

2，代码框能否美化下，如下截图
![image](https://user-images.githubusercontent.com/65819267/166403246-d7011939-69e7-45f6-b35c-3ec5b3090c22.png)
演示网址 https://blog.orangii.cn/2022/bt-panel-enable-http3/

**Comment by n0099** [comment]
解决截断：
```css
word-break: normal
```

**Comment by seatonjiang** [comment]
英文单词标题被截断的问题解决了，代码段建议使用插件。
