### ISSUE TITLE
升级插件会导致出现问题内核错误

### ISSUE THREAD

**Issue by jiuchengyixi00** [xb2016/Kratos#503]
![image](https://user-images.githubusercontent.com/40533607/166699789-f681abf1-d6ff-4fe3-978c-c2d1f39ce517.png)

**Comment by seatonjiang** [comment]
升级4.1.3试一下

**Comment by jiuchengyixi00** [comment]
就是因为升级了4.1.3才会这个样子

**Comment by jiuchengyixi00** [comment]
4.1.2还是好的

**Comment by SiloRanger** [comment]
主题设置里, 切换下Gravatar 加速服务

**Comment by jiuchengyixi00** [comment]
我并没有设置这个

**Comment by jiuchengyixi00** [comment]
而且当以上传形式，上传4.1.3会导致网站崩溃update.php?action=upload-theme 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by cnrock** [comment]
> 我并没有设置这个

作者的意思是在后台主题设置里面切换一下，或者索性关闭吧。

还好你提了这个问题，我今天升级也遇到了，现在解决了。

![g1](https://user-images.githubusercontent.com/8827567/167077215-9fbcb837-4339-4b90-b09e-fd807ae86c5b.png)

**Comment by jiuchengyixi00** [comment]
> > 我并没有设置这个
> 
> 作者的意思是在后台主题设置里面切换一下，或者索性关闭吧。
> 
> 还好你提了这个问题，我今天升级也遇到了，现在解决了。
> 
> ![g1](https://user-images.githubusercontent.com/8827567/167077215-9fbcb837-4339-4b90-b09e-fd807ae86c5b.png)

**Comment by jiuchengyixi00** [comment]
Gravatar加速服务我是一直关闭的，所以我才不明白到底是哪里的问题

**Comment by jiuchengyixi00** [comment]
我明白了，谢谢大家，知道怎么回事了
