### ISSUE TITLE
更新后没有了返回顶部

### ISSUE THREAD

**Issue by q2316367743** [xb2016/Kratos#504]
更新后没有了返回顶部

PHP 版本：7.4.27
Kratos 版本：4.1.3
WordPress 版本：5.9.3

**Comment by n0099** [comment]
主题设置里开启

**Comment by erogakuen** [comment]
这个自带返回顶部吗，找了一圈没找到啊？

**Comment by n0099** [comment]
右下角

**Comment by erogakuen** [comment]
之前装4.1.2没发现有返回顶部，就自己添加代码弄了一个跟搜索悬浮标志一样的返回顶部标志，升级4.1.3之后看这里说有自带，刚才把自己添加的去除后，才看到。
由于两个基本一模一样，重叠在一起都没发现，不过页面上升速度确实有区别

**Comment by citratecycle** [comment]
PHP 版本：8.0.18
Kratos 版本：4.1.3
WordPress 版本：5.9.3
User Agent 信息：Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1

用iOS Safari打开网页后，看不到返回顶部按钮，用windows电脑打开显示正常。

另外我在「主题设置」中也没找到关于这个返回顶部按钮的选项啊？

我的网站：[citrate.cn](https://citrate.cn)

**Comment by seatonjiang** [comment]
@citratecycle 这里测试没有问题
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/57834639/204130499-b94f883c-ef24-4fbc-abd5-f67dfb0b259b.png">
