### ISSUE TITLE
统计代码为什么不插入到head？

### ISSUE THREAD

**Issue by wkingnet** [xb2016/Kratos#505]
不论是51la、百度、google，都提示说要将统计代码插入到head标签内，但kratos是将代码插入到了footer里。

请问这么做有什么好处吗？会不会影响代码功能？

![1](https://user-images.githubusercontent.com/57652989/166877104-34844138-1527-498b-868a-67bd3b982c06.png)

**Comment by n0099** [comment]
>请问这么做有什么好处吗？

无

**Comment by seatonjiang** [comment]
这个地方已经优化了，建议添加异步的统计代码到head中
