### ISSUE TITLE
请问如何禁用图片灯箱功能

### ISSUE THREAD

**Issue by g93920079** [xb2016/Kratos#507]
感觉主题自带的灯箱功能有点弱，想通过插件实现灯箱效果，但是启用了插件后会导致和原灯箱效果重叠

**Comment by n0099** [comment]
主题设置轮播图删除所有项

**Comment by g93920079** [comment]
> 主题设置轮播图删除所有项

大佬，我只找到首页轮播，能再说的详细点吗？
![1652444634(1)](https://user-images.githubusercontent.com/31822907/168282412-93733d71-7ca3-430a-be97-178b5acd2b07.png)

**Comment by n0099** [comment]
您说的灯箱是指什么

**Comment by g93920079** [comment]
> 您说的灯箱是指什么

就是鼠标点击图片，图片会放大，然后背景变黑那种

**Comment by n0099** [comment]
建议换https://github.com/fengyuanchen/viewerjs
cc @seatonjiang

**Comment by g93920079** [comment]
> 建议换https://github.com/fengyuanchen/viewerjs cc @seatonjiang

请问大佬，有更换步骤吗？

**Comment by n0099** [comment]
我是说建议主题作者换成这个库

**Comment by jalena** [comment]
目前这个效果真的拉跨！

**Comment by seatonjiang** [comment]
@jalena @g93920079 新增了一个灯箱的控制开关，后期考虑更换一个效果更好的，更新新版本即可。

<img width="435" alt="image" src="https://user-images.githubusercontent.com/57834639/204134657-cb99fab8-ba81-4cf6-b19c-a9c0aa893598.png">

**Comment by jalena** [comment]
> @jalena @g93920079 新增了一个灯箱的控制开关，后期考虑更换一个效果更好的，更新新版本即可。
> 
> <img alt="image" width="435" src="https://user-images.githubusercontent.com/57834639/204134657-cb99fab8-ba81-4cf6-b19c-a9c0aa893598.png">

给力。

**Comment by n0099** [comment]
> > 建议换[fengyuanchen/viewerjs](https://github.com/fengyuanchen/viewerjs) cc @seatonjiang
> 
> 请问大佬，有更换步骤吗？

1. 通过wp的js/css依赖树管理（[wp_enqueue_script](https://developer.wordpress.org/reference/functions/wp_enqueue_script/)和[wp_enqueue_style](https://developer.wordpress.org/reference/functions/wp_enqueue_style/)） 或 直接在header.php里加<script>和<link rel=stylesheet>标签 以给您的（子）主题引入viewerjs的[js](https://github.com/fengyuanchen/viewerjs/blob/main/dist/viewer.min.js)和[css](https://github.com/fengyuanchen/viewerjs/blob/main/dist/viewer.min.css)
2. 在您子主题主js（必定enqueue的js）中添加以下js：
```js
$(window).on('load', () => {
    if (window.Viewer === undefined) return;
    const imgContainer = document.querySelector('.article .content');
    if (imgContainer === null) return;
    window.viewerjs = new Viewer(imgContainer, {
        url: imgEl => imgEl.getAttribute('data-src') || imgEl.getAttribute('src'),
        inheritedAttributes: ['decoding', 'loading', 'data-src', 'class']
    });
});
```
