### ISSUE TITLE
请问如何解决插入图片时引起的警告问题

### ISSUE THREAD

**Issue by phongfire** [xb2016/Kratos#508]
您好，我在写文章插入图片时遇到了如下状况：
Warning: strpos(): Empty needle in /usr/local/lighthouse/softwares/wordpress/wp-content/themes/kratos-main/inc/theme-article.php on line 34
想请问一下如何解决这个问题？

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/bbf16b417ae9abc288735e67dd9dbda853a29acf/inc/theme-article.php#L34

**Comment by seatonjiang** [comment]
这个问题怎么样才能复现呢？

**Comment by seatonjiang** [comment]
这个问题是由于腾讯云的轻量镜像默认不配置WordPress地址导致的，更新新版本即可解决，不过建议是把这里补充上，不然这里功能不会生效。
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/57834639/204132010-ba3cc1d4-8c6c-4f49-9f4f-f0bffc1e1c1f.png">
