### ISSUE TITLE
更新后，页面排版错乱。

### ISSUE THREAD

**Issue by sunyang2160** [xb2016/Kratos#509]
更新后网页排版错乱，WP后台上部显示

Warning: Trying to access array offset on value of type bool in /www/wwwroot/8.136.102.xx/wp-content/themes/kratos-4.0.3/inc/theme-core.php on line 212

Warning: Undefined array key "" in /www/wwwroot/8.136.102.xx/wp-content/themes/kratos-4.0.3/inc/theme-core.php on line 212

Warning: Trying to access array offset on value of type bool in /www/wwwroot/8.136.102.xx/wp-content/themes/kratos-4.0.3/inc/theme-core.php on line 212

Warning: Undefined array key "" in /www/wwwroot/8.136.102.xx/wp-content/themes/kratos-4.0.3/inc/theme-core.php on line 212

本人纯小白，无编程知识，希望各位大神帮忙解决，谢谢

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/bbf16b417ae9abc288735e67dd9dbda853a29acf/inc/theme-core.php#L212

去主题设置里调一下gravatar加速服务器设置

**Comment by sunyang2160** [comment]
> https://github.com/seatonjiang/kratos/blob/bbf16b417ae9abc288735e67dd9dbda853a29acf/inc/theme-core.php#L212
> 
> 去主题设置里调一下gravatar加速服务器设置

谢谢，我在宝塔里把PHP8.0改为PHP7.4，好像就行了。

**Comment by n0099** [comment]
我是php81

**Comment by sunyang2160** [comment]
> 我是php81

谢谢你！

**Comment by wkingnet** [comment]
因为你开启了其他插件的gravatar加速功能，和kratos冲突了。你到kratos设置里，把gravatar加速关了就行

**Comment by seatonjiang** [comment]
问题修复了，这个并不是冲突的问题，下个版本更新即可。
