### ISSUE TITLE
iOS端一级标题显示有问题

### ISSUE THREAD

**Issue by citratecycle** [xb2016/Kratos#510]
PHP 版本：8.0.18
Kratos 版本：4.1.3
WordPress 版本：5.9.3
User Agent 信息：Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1

![image](https://user-images.githubusercontent.com/48681002/169511907-34e0b20a-0632-4932-ad81-4ce12d110739.png)

可以看到一级标题过小

[测试页面](https://citrate.cn/title_test)

**Comment by citratecycle** [comment]
我看了一下这个应该不是iOS本身的问题，当页面长宽比逐渐变小，到1.1左右的时候，就会出现这个问题

**Comment by citratecycle** [comment]
看了下，应该和[这一行](https://github.com/seatonjiang/kratos/blob/main/style.css#L1339)，在页面kuandu 小于768px的时候，一级标题的字号从34px缩小到22px。应该需要把二~六级标题都对应缩小才行。

另外这个css好像是托管在 https://cdn.seatonjiang.com/kratos/4.1.3/style.css?ver=4.1.3 这里的？我修改本地的style.css也没用来着。

**Comment by n0099** [comment]
> 另外这个css好像是托管在 https://cdn.seatonjiang.com/kratos/4.1.3/style.css?ver=4.1.3 这里的？我修改本地的style.css也没用来着。

建议!important

**Comment by n0099** [comment]
22/34=0.647058824

请问这到底缩小多少倍

**Comment by citratecycle** [comment]
> 22/34=0.647058824
> 
> 请问这到底缩小多少倍

![屏幕截图 2022-05-21 003958](https://user-images.githubusercontent.com/48681002/169573802-a7493a67-139d-4d9a-8ad0-fa16bd34a5c3.png)
![屏幕截图 2022-05-21 004040](https://user-images.githubusercontent.com/48681002/169573813-e752dae5-8d9e-4444-824a-38d4a76acd75.png)

我猜这个原意是只缩小主标题来着，但是实际上也影响了文章内标题

**Comment by citratecycle** [comment]
> > 另外这个css好像是托管在 https://cdn.seatonjiang.com/kratos/4.1.3/style.css?ver=4.1.3 这里的？我修改本地的style.css也没用来着。
> 
> 建议!important

我试了一下，在`style.css`加`!impotant`好像没用……我把“静态资源加速”关了它就读我本地的CSS了

**Comment by n0099** [comment]
建议子主题

**Comment by seatonjiang** [comment]
这个问题修复了，但是不建议在文章中使用h1，因为标题已经是h1了，这样对收录不友好。

![image](https://user-images.githubusercontent.com/57834639/170627406-c17f703c-ae9d-42d8-9c6d-6071bcf56b94.png)
