### ISSUE TITLE
使用wordpress download manager插件后，插件生成的页面有错误

### ISSUE THREAD

**Issue by wkingnet** [xb2016/Kratos#511]
使用wordpress download manager插件后，在插件内上传的附件，插件会生成一个下载页面。这个下载页面kratos会显示错误。

插件我使用了extened templetes模板

![1](https://user-images.githubusercontent.com/57652989/170536482-2007523a-74ec-4326-90bc-f0a2b7db79c9.png)

然后我依据错误提示，把kratos的single.php改了一下，也不知道我改的对不对？

```
<?php
$cat_id = isset($term_id) ? get_the_category()[0]->term_id : false;
$if_parent = TRUE;
$breadcrumb = "";
while ($if_parent == TRUE) {
    $cat_object = get_category($cat_id);
    $cat = isset($cat_object->term_id) ? $cat_object->term_id : false;
    $categoryURL = get_category_link($cat);
    $name = isset($cat_object->name) ? $cat_object->name : false;
    $cat_id = isset($cat_object->parent) ? $cat_object->parent : false;
```

**Comment by seatonjiang** [comment]
这个问题修复了，面包屑导航不应用到附件页面。
![image](https://user-images.githubusercontent.com/57834639/170622595-a60accd5-034b-47ab-bd32-6363f4a37db0.png)

**Comment by wkingnet** [comment]
更新到4.1.4  我这里仍然报错  

![1](https://user-images.githubusercontent.com/57652989/170883181-cb735e7c-5bcf-46de-a093-b84485a924be.png)

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/069c0cfc9719d0e60875362d11a0868cfca32f1d/single.php#L30
