### ISSUE TITLE
有没有计划增加说说和专题功能？

### ISSUE THREAD

**Issue by hou-solifugus** [xb2016/Kratos#519]
请问有没有计划增加说说和专题功能？

说说能增加写作的频率，可能会当作一个比较基础的想法记录的空间。

专题能够增加体系化输出后的汇总，也能有助于体系化思考。

**Comment by n0099** [comment]
建议插件

**Comment by iamlvtu** [comment]
自己DIY就可以了！

**Comment by seatonjiang** [comment]
主线版本不做这样的功能，可以自定义通过子主题自己做一个
