### ISSUE TITLE
版本升级及老版本删除问题

### ISSUE THREAD

**Issue by sc8cn** [xb2016/Kratos#520]
wordpress6.0版本，显示主题有新版本，点升级无效。下载主题包直接安装，不能替换原主题版本。新版本安装后，原版本主题点击删除，提示：”删除失败：请求的主题不存在。“特别是这个老版本不能删除的问题，升级几次，留的版本就太多了

**Comment by seatonjiang** [comment]
检查一下目录权限

**Comment by sc8cn** [comment]
您好，来信已到达目的地，我的主人将择日阅读，谢谢！

**Comment by sc8cn** [comment]
> 检查一下目录权限

通过WORDPRESS直接安装的主题是可以删除的，就是这个上传压缩包的主题发现不能删除

**Comment by n0099** [comment]
检查一下wp-content/themes目录及其子目录权限，www用户是否对其有rw权限
