### ISSUE TITLE
支持php7.2的kratos主题

### ISSUE THREAD

**Issue by noarsark** [xb2016/Kratos#527]
由于服务器配置不够，能否有支持php7.2版本的kratos主题

**Comment by n0099** [comment]
主题版本4.1.0之前应该是支持>php7.2的
https://github.com/seatonjiang/kratos/commit/cd0826c8528edb3a200d91b2a68f2cf3138d1b78#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L6
https://github.com/seatonjiang/kratos/commit/49a2ffbd38bfc4fbe3372233061abb8c2c8b88cb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6

**Comment by noarsark** [comment]
感谢，后来发现配置支持就升级了php版本
