### ISSUE TITLE
文章后统一设定

### ISSUE THREAD

**Issue by xianglujun** [xb2016/Kratos#528]
希望可以在文章末尾新增一个统一设定，比如自定义的一段话，或者自定义版权的统一设定，这样就再好不过了

**Comment by n0099** [comment]
我的建议是：利用wp的[子主题功能](https://developer.wordpress.org/themes/advanced-topics/child-themes/)来对[single.php](
https://github.com/seatonjiang/kratos/blob/main/single.php)进行自定义

**Comment by xianglujun** [comment]
您好，您的邮件已经收到！祝您开心！

**Comment by xianglujun** [comment]
主要是对php不太熟悉，能够小白一点就更好啦

**Comment by n0099** [comment]
提请您执行下述bash：
```bash
wp=您的wordpress所在目录
cd ${wp}/wp-content/themes
mkdir kratos-child
echo '/*
Theme Name: Kratos Child
Template: kratos
*/' > kratos-child/style.css
cp kratos{,-child}/single.php
```
然后对`kratos-child/single.php`文件内容进行修改
最后在wp后台中切换当前主题为这个子主题`kratos-child`

如果您的需求只是添加静态文本您只需要知道如何写html而不需要php

**Comment by xianglujun** [comment]
您好，您的邮件已经收到！祝您开心！
