### ISSUE TITLE
顶部导航栏只显示二级菜单，能不能设置多级菜单？

### ISSUE THREAD

**Issue by Loryrry** [xb2016/Kratos#534]
二级分类菜单不够用，需要至少三级，但是无法显示

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/7b8ceffeba693b0cc02721769b578a60112e0c6f/inc/theme-navwalker.php
作者没有实现递归显示无限深度的目录层级

**Comment by seatonjiang** [comment]
博客一般就是一级导航，最多二级够用了，暂时没有计划支持三级导航。
