### ISSUE TITLE
请问是否可以增加“搜索特定分类下的文章”这个功能？

### ISSUE THREAD

**Issue by g93920079** [xb2016/Kratos#535]
请问是否可以增加“搜索特定分类下的文章”这个功能？默认的搜索会把文章中的所有相关内容都搜索出来

**Comment by n0099** [comment]
使用第三方搜索插件，如 https://www.wpbeginner.com/showcase/12-wordpress-search-plugins-to-improve-your-site-search/

**Comment by seatonjiang** [comment]
同样建议使用插件实现。
