### ISSUE TITLE
请问有考虑出个暗黑模式吗？

### ISSUE THREAD

**Issue by mikuwife** [xb2016/Kratos#536]

**Comment by n0099** [comment]
建议无脑反色img/canvas之外的所有dom

**Comment by yuyang97BU** [comment]
不是很懂具体怎么操作。。能详细说一下吗？我想把文章背景改成黑的文章字体改成白的，谢谢

**Comment by n0099** [comment]
1. 创建子主题：https://developer.wordpress.org/themes/advanced-topics/child-themes/
2. 在style.css中添加可实现您的需求的css

**Comment by TylerDurdenT** [comment]
额外CSS中输入

@media (prefers-color-scheme: dark) {
  html {
    filter: invert(100%);
  }

}

**Comment by 14thDay** [comment]
> 额外CSS中输入
> 
> @media (prefers-color-scheme: dark) { html { filter: invert(100%); }
> 
> }

试过，但是背景图和你别的插入的图也都会被invert
别的插入的图我能找到tag再invert一次，背景/顶部栏那个图我有点菜没找到是什么tag

**Comment by n0099** [comment]
> 找到tag再invert一次

您为什么不直接

> 反色img/canvas之外

？

即`*:not(img)`

**Comment by a-user-xing** [comment]
> > 找到tag再invert一次
> 
> 您为什么不直接
> 
> > 反色img/canvas之外
> 
> ？
> 
> 即`*:not(img)`

在使用
@media (prefers-color-scheme: dark){html{filter: invert(100%);}img{filter: invert(100%);}}
之后，页脚和页眉显示也是不正常的（打开了图片导航），以及，文章标题前的分类颜色也不正常。

**Comment by seatonjiang** [comment]
Kratos 暂时没有计划支持暗黑模式，可以关注 Fraise 主题。
