### ISSUE TITLE
文章目录生成

### ISSUE THREAD

**Issue by xianglujun** [xb2016/Kratos#537]
请问比较长的文章，怎么样可以生成目录呢？目前在配置中没有找到

**Comment by n0099** [comment]
什么叫生成目录
本主题有一个功能可在右侧小工具栏上面显示根据文中的`<h1><h2>`等html标签层级来自动生成的目录列表

**Comment by xianglujun** [comment]
您好，您的邮件已经收到！祝您开心！

**Comment by dstweihao** [comment]
> 什么叫生成目录 本主题有一个功能可在右侧小工具栏上面显示根据文中的`<h1><h2>`等html标签层级来自动生成的目录列表

你好，我这边设置了，怎么是空白的，没有显示小工具栏，谢谢了，是文章那个布局，我显示有右侧栏的了。

**Comment by xianglujun** [comment]
您好，您的邮件已经收到！祝您开心！

**Comment by n0099** [comment]
> > 什么叫生成目录 本主题有一个功能可在右侧小工具栏上面显示根据文中的`<h1><h2>`等html标签层级来自动生成的目录列表
> 
> 你好，我这边设置了，怎么是空白的，没有显示小工具栏，谢谢了，是文章那个布局，我显示有右侧栏的了。

文章里有`<h1><h2>`等html标签吗
您随便添加别的小工具看看右侧会显示吗

**Comment by dstweihao** [comment]
> > > 什么叫生成目录 本主题有一个功能可在右侧小工具栏上面显示根据文中的`<h1><h2>`等html标签层级来自动生成的目录列表
> > 
> > 
> > 你好，我这边设置了，怎么是空白的，没有显示小工具栏，谢谢了，是文章那个布局，我显示有右侧栏的了。
> 
> 文章里有`<h1><h2>`等html标签吗 您随便添加别的小工具看看右侧会显示吗

不好意思。。是我不会用导致的，我还以为在主题设置里设置就行了，现在已经弄好了，需要添加小工具的，麻烦了。
