### ISSUE TITLE
cdn.seatonjiang.com的通配符SSL证书已过期

### ISSUE THREAD

**Issue by nyable** [xb2016/Kratos#543]
你好，在开启`静态资源加速`选项后，js、css等静态资源从`cdn.seatonjiang.com`加载，其通配符证书`*.seatonjiang.com`已于今日-2022年11月10日星期四 11:46:40 过期。目前因为浏览器拒绝加载静态资源导致样式错乱。

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/201029553-7a3d04f5-2b31-4c7d-84a9-18b95515bcc9.png)

已经替换了新的证书，等全网缓存刷新即可。
