### ISSUE TITLE
IE浏览器和手机端页面乱了，chrome浏览器能正常访问。

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#544]
IE浏览器和手机端页面乱了，chrome浏览器能正常访问。是今天刚发现的，不知道是不是最近更新到6.1后造成的。

**Comment by seatonjiang** [comment]
![image](https://user-images.githubusercontent.com/57834639/201029513-97b2e53e-bc4d-4885-82ee-40f07a404742.png)

CDN域名证书过期导致，已经替换新的证书，现在已经恢复了。

**Comment by n0099** [comment]
#543
