### ISSUE TITLE
文章修改页报错：Failed to load plugin url: http://cdn.seatonjiang.com/krotos/4.1.4/assets/js/buttons/more.js

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#547]
文章修改页报错：Failed to load plugin url: http://cdn.seatonjiang.com/krotos/4.1.4/assets/js/buttons/more.js
请教是什么错误呢？

**Comment by seatonjiang** [comment]
更改了主题名字吗？资源地址是 https://cdn.seatonjiang.com/kratos/4.1.4/assets/js/buttons/more.js

**Comment by Justmekarl** [comment]
没有修改。是我打错了。目前又不报错了。很奇怪。

**Comment by n0099** [comment]
#543
