### ISSUE TITLE
点击图片库的图片，文章标题处显示乱字符，是否哪里配置有误？

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#549]
![d1fe2420526d1f56d8c8cf018a0cd8f](https://user-images.githubusercontent.com/117895875/201825900-cdb827e5-9f71-44db-9eb1-110b555bd34e.png)
点击图片库的图片，文章标题处显示乱字符，是否哪里配置有误？（见上图）

**Comment by n0099** [comment]
这是上传时图片原文件名的md5
https://github.com/seatonjiang/kratos/blob/82841130b3bf6d8e8f5252390456f7f71f10b11b/inc/theme-core.php#L275

**Comment by Justmekarl** [comment]
好的，多谢回答。
