### ISSUE TITLE
请问最新版本不支持php8.1吗，我切换到php8.1 页面很多warning报错

### ISSUE THREAD

**Issue by fengjun8** [xb2016/Kratos#551]
请问最新版本不支持php8.1吗，我切换到php8.1 页面很多warning报错

**Comment by fengjun8** [comment]
wordpress版本6.1.1

**Comment by n0099** [comment]
哪儿

**Comment by seatonjiang** [comment]
建议使用PHP8,目前WP对8.1还是不够适配

**Comment by n0099** [comment]
> 目前WP对8.1还是不够适配

事实核查：截止wp6.1，wpcore本身已经完成了对php8.2的兼容性： https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/ 当然主题插件生态跟wpcore无关也是最难升上来的，但phpcore人本身就保持高度的BC（向前兼容性）不中断
我也用的php81没在nginx的errorlog中看到有来自本主题而非我用的插件的phpfpm warn/error

**Comment by jalena** [comment]
PHP 版本：8.1.12
Kratos 版本：4.1.4
WordPress 版本：6.1.1

你看看我的，没有一点问题呢！

[doker部署wordpress](https://jalena.bcsytv.com/archives/2367)

**Comment by seatonjiang** [comment]
@fengjun8 在8.1的环境下测试了一下，目前只有WP自身的Deprecated问题，但主题没有发现任何问题，能提供一下报错的信息吗？

**Comment by seatonjiang** [comment]
麻烦测试是否为主题的报错，本地测试 8.2.1 也是正常的，有问题麻烦及时反馈。
