### ISSUE TITLE
网页在微信里分享的小图标应该怎么设置？

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#552]
![660f9aea2820ad7717f88efd3f3a0bc](https://user-images.githubusercontent.com/117895875/202609330-c2a1f7fa-ef1e-4c39-adc5-2972868f2037.png)
请问这个小图标应该怎么设置？我的网站文章分享都是灰色的，没有图标。

**Comment by n0099** [comment]
这是[opengraph](ogp.me)
```html
<meta property="og:image" content="url/to/ur/image" />
```

与此同时本主题已经有了[schema.org](https://schema.org/BlogPosting)的[meta](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop)：
https://github.com/seatonjiang/kratos/blob/bc906b6c83b43bb5f7912bfe859cbfd6436587e6/header.php#L22
https://github.com/seatonjiang/kratos/blob/9f499eaf50c58c72e1daef577e9ef70cf6ab9d64/inc/theme-setting.php#L105

**Comment by Justmekarl** [comment]
![1668835231429](https://user-images.githubusercontent.com/117895875/202835688-899cc53f-eb01-4415-bb18-754989b35a86.png)
谢谢您的回复。我目前正在使用本主题。同一个页面，有时候分享会有小图标，有时候反复尝试又没有了。请教您，应该什么设置，确保正常使用？谢谢

**Comment by n0099** [comment]
> ![1668835231429](https://user-images.githubusercontent.com/117895875/202835688-899cc53f-eb01-4415-bb18-754989b35a86.png) 谢谢您的回复。我目前正在使用本主题。同一个页面，有时候分享会有小图标，有时候反复尝试又没有了。请教您，应该什么设置，确保正常使用？谢谢

建议反复执行`curl 文章url | grep 'itemprop="image"'`观察

**Comment by Justmekarl** [comment]
![1668944323889](https://user-images.githubusercontent.com/117895875/202899923-26103acf-8360-4360-8c62-c671181b7008.png)
![1668944441468](https://user-images.githubusercontent.com/117895875/202899989-ed0dcc26-caf0-4e05-afc0-2232b7c7941f.jpg)
感谢回复！我用curl出来的地址，跟我在微信中分享的小图标，不是一个图片。

**Comment by n0099** [comment]
那就grep您在微信中看到的那个图片的url，看看是哪个tag在引用

**Comment by Justmekarl** [comment]
我通过QQ浏览器分享就正常了。谢谢！

**Comment by n0099** [comment]
那您之前用啥分享的
您不能直接在微信里发url吗？
