### ISSUE TITLE
如何修改CDN上的css样式文件？

### ISSUE THREAD

**Issue by sheldonwxd2021** [xb2016/Kratos#555]
LOGO在PC上的尺寸太小，如何自定义调整一下？

**Comment by n0099** [comment]
1. 关闭主题设置的使用cdn加速静态资源
2. 创建[子主题](https://developer.wordpress.org/themes/advanced-topics/child-themes/)在style.css中写有关css

**Comment by seatonjiang** [comment]
本地修改CSS，覆盖CDN的即可，或者你可以自建CDN也可以。
