### ISSUE TITLE
请问这个模板支持内网（连接不了互联网）使用吗？

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#556]
我记得前几天版主主机认证失效，模板就不能用了。请问这个模板支持内网（连接不了互联网）使用吗？

**Comment by n0099** [comment]
不启用引用cdn.seatonjiang.com的静态资源就行
建议直接[autoptimize](https://wordpress.org/plugins/autoptimize/)

**Comment by Justmekarl** [comment]
![6b7f4989cbc643c990e98fe1d7ed071](https://user-images.githubusercontent.com/117895875/203001303-d3fcccc9-8108-4ae2-add6-9db7bda2abc2.png)
"不启用引用cdn.seatonjiang.com的静态资源就行",是指得把上图“静态资源”设置为禁用，对吗？
”建议直接[autoptimize](https://wordpress.org/plugins/autoptimize/)”，是指把静态资源设置为禁用后，通过这个插件去优化网站加速，对吗？谢谢您的回复。

**Comment by seatonjiang** [comment]
cdn.seatonjiang.com 已经恢复了，内网使用的话，把静态加速关掉，就自动加载本地资源了

**Comment by Justmekarl** [comment]
好的。感谢回复！

**Comment by n0099** [comment]
> ![6b7f4989cbc643c990e98fe1d7ed071](https://user-images.githubusercontent.com/117895875/203001303-d3fcccc9-8108-4ae2-add6-9db7bda2abc2.png) "不启用引用cdn.seatonjiang.com的静态资源就行",是指得把上图“静态资源”设置为禁用，对吗？ ”建议直接[autoptimize](https://wordpress.org/plugins/autoptimize/)”，是指把静态资源设置为禁用后，通过这个插件去优化网站加速，对吗？谢谢您的回复。

1. 是
2. autoptimize这类插件是把每个html页上引用的所有复数个js/css文件都合并进1个文件（分别js/css）并对js引入默认设置`<sciprt async>`从而加快first contentful paint和largest contentful paint的时间点
  当然如果您能自己分清楚有哪些js/css功能上是可选的不那么优先加载的（所以他们可以仍然保持独立的请求而不是合并）您也可以手动从autoptimize的聚合中排除掉他们从而进一步减少其生成的合并js/css文件大小
