### ISSUE TITLE
请问侧边栏的“分类”等样式如何修改？

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#557]
这个主题是我最喜欢的中文主题，简洁大气。我想稍微修改一下侧边栏的样式，比如将分类做个底部图片什么的。请问在哪里修改？是否允许修改主题呢？谢谢

**Comment by n0099** [comment]
建议学习child-theme与html和php基础

**Comment by Justmekarl** [comment]
好的，非常感谢！有没有推荐的child-theme学习材料？

**Comment by n0099** [comment]
https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by Justmekarl** [comment]
Thanks so much.
