### ISSUE TITLE
如何控制页面访问权限？

### ISSUE THREAD

**Issue by Justmekarl** [xb2016/Kratos#558]
请问这个模板使用什么插件控制用户访问权限比较好？就是分不同角色来设置访问页面的权限？哪个插件跟这个主题匹配得比较好？谢谢

**Comment by n0099** [comment]
随便什么插件都行
我用的 https://wordpress.org/plugins/user-role-editor/

**Comment by Justmekarl** [comment]
谢谢！Thanks for your great support!

**Comment by Justmekarl** [comment]
继续请教一下。我试用了user-role-editor插件，功能挺强大的。但是好像是对于网站功能权限的分配比较多。如何设置不同角色访问不同的栏目文章或者页面呢？这个是不是做不到啊？我看这个插件，目前只能设置允许访问隐私页面（文章）。

**Comment by n0099** [comment]
您的需求只是限制不同role的用户能访问不同的文章？那您可以自己写：
主要是在
- [pre_get_posts](https://developer.wordpress.org/reference/hooks/pre_get_posts/)：对所有WP_Query的预处理
- [comment_feed_where](https://developer.wordpress.org/reference/hooks/comment_feed_where/)：WP_Query查询文章评论时的预处理
- [template_redirect](https://developer.wordpress.org/reference/hooks/template_redirect/)：直接访问文章slug url时的过滤，如 https://wordpress.stackexchange.com/questions/91900/how-to-force-a-404-on-wordpress/92176#92176

等hooks上对当前登录用户WP_User的[role或capabilities](https://wordpress.org/support/article/roles-and-capabilities/)上做判断并决定是否拦截


对于本kratos主题而言，如果您使用了主题提供的文章聚合和最近评论widget那您也需要fork他们：
https://github.com/seatonjiang/kratos/blob/bbcae675624ad0daf4bc3bb4ccc4d7b7ce059f86/inc/theme-widgets.php#L414
https://github.com/seatonjiang/kratos/blob/bbcae675624ad0daf4bc3bb4ccc4d7b7ce059f86/inc/theme-widgets.php#L505
并修改其查询sql（因为主题作者在这里直接查询了raw sql所以无法被hooks修改）：
https://github.com/seatonjiang/kratos/blob/bbcae675624ad0daf4bc3bb4ccc4d7b7ce059f86/inc/theme-widgets.php#L82
https://github.com/seatonjiang/kratos/blob/bbcae675624ad0daf4bc3bb4ccc4d7b7ce059f86/inc/theme-widgets.php#L146


根据需求您可能还需要对wp自带的文章和评论rss atom feed进行过滤：https://wordpress.stackexchange.com/questions/126174/disable-comments-feed-but-not-the-others/126177#126177
以及对导航菜单进行过滤： https://wordpress.stackexchange.com/questions/31748/dynamically-exclude-menu-items-from-wp-nav-menu/31753#31753

**Comment by n0099** [comment]
当然阁下也可选择直接使用现成的高度集成的开源或商业插件：
https://kinsta.com/blog/wordpress-membership-plugins/
https://www.wpbeginner.com/plugins/5-best-wordpress-membership-plugins-compared/
https://optinmonster.com/wordpress-membership-site-plugins/
https://www.hostinger.com/tutorials/best-wordpress-membership-plugins

**Comment by Justmekarl** [comment]
感谢这么专业的回复。自己写水平还不够。我试试看插件吧。谢谢回复！
