### ISSUE TITLE
希望作者能够支持左侧菜单栏组件

### ISSUE THREAD

**Issue by tanjie123** [xb2016/Kratos#560]
兼容https://wordpress.org/plugins/advanced-sidebar-menu/

**Comment by n0099** [comment]
这插件用了哪些wpcore的hooks？
https://github.com/lipemat/advanced-sidebar-menu/search?q=add_action
https://github.com/lipemat/advanced-sidebar-menu/search?q=do_action
https://github.com/lipemat/advanced-sidebar-menu/search?q=add_filter
https://github.com/lipemat/advanced-sidebar-menu/search?q=apply_filters
