### ISSUE TITLE
没找到地方修改：有设置特色图的就显示，没设置的就显示标题和内容缩略

### ISSUE THREAD

**Issue by cpcc** [xb2016/Kratos#561]
PHP 版本：7.4.28
Kratos 版本：4.1.5
WordPress 版本：6.1.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

想设置成有特色图的就显示特色图，没设置的的就显示标题和内容缩略

**Comment by n0099** [comment]
自己改 https://github.com/seatonjiang/kratos/blob/29366cb136dca1f205237bfbbf9f643dab634c6b/pages/page-content.php#L20

**Comment by cpcc** [comment]
> 自己改
> 
> https://github.com/seatonjiang/kratos/blob/29366cb136dca1f205237bfbbf9f643dab634c6b/pages/page-content.php#L20

收到

**Comment by seatonjiang** [comment]
问题已经长时间没有回复，暂时先关闭，仍有疑问可以随时打开反馈。
