### ISSUE TITLE
启用Redis后，小工具里“目录”的样式显示异常

### ISSUE THREAD

**Issue by Reius** [xb2016/Kratos#562]
启用插件“Redis Object Cache”后，文章页面中小工具里“目录”的样式显示异常，经过查找，似乎是下边两行代码顺序颠倒导致的。

https://github.com/seatonjiang/kratos/blob/1b04069b8591a981b9dc6c08f2f4748d7545b142/inc/theme-widgets.php#L614-L615

**Comment by seatonjiang** [comment]
发现问题了，下个版本推送修复，更新版本后，刷新redis缓存即可。
