### ISSUE TITLE
主题中的热度浏览量如何修改

### ISSUE THREAD

**Issue by vvvmao** [xb2016/Kratos#564]
比如某篇文章100热度，如何修改成1000热度这个样子 修改哪个文件 ，由什么改成什么？不胜感激！！！

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/e61b84b96c56236eb6da308575dacd29f1398c7c/inc/theme-article.php#L78
```sql
UPDATE wp_postmeta SET meta_value = 您的新值 WHERE meta_key = "views" AND post_id = 您的文章ID
```

**Comment by seatonjiang** [comment]
不用这么麻烦，在编辑文章的页面，有个自定义字段，然后编辑就行了 views 是浏览量，love 是点赞量，改完点更新就可以

![image](https://user-images.githubusercontent.com/57834639/212445187-ed25890b-2ef8-4857-8479-ff24a28fad72.png)

![image](https://user-images.githubusercontent.com/57834639/212445209-69a7b1f9-da49-47f8-b6eb-df1bf52f2c6b.png)
