### ISSUE TITLE
4.15版本顶部菜单如何设置二级分类？

### ISSUE THREAD

**Issue by ajiafe** [xb2016/Kratos#565]
如题

**Comment by n0099** [comment]
在`wp-admin/menu.php`里把菜单项往右拖就是增加层级深度

**Comment by heybugs** [comment]
> 

非常感谢，已经ok了

**Comment by ajiafe** [comment]
> 在`wp-admin/menu.php`里把菜单项往右拖就是增加层级深度

非常感谢，已经ok了
