### ISSUE TITLE
请问为什么页面没看到预览图中右侧的如下所示的部分，只有一侧

### ISSUE THREAD

**Issue by sdnasldksl** [xb2016/Kratos#566]
[](url)](https://user-images.githubusercontent.com/122809317/212714339-593e2ca0-02c8-4109-a361-57739233b173.png)

**Comment by sdnasldksl** [comment]
就是本来下面的主体是分左右部分的，我现在看不到右侧的

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/issues/563#issuecomment-1382632583

**Comment by sdnasldksl** [comment]
![image](https://user-images.githubusercontent.com/122809317/212717363-8e498880-c78e-4895-a5c6-6929c47d6c7b.png)
双栏设置是这个吗，我设置了好像没什么变化

**Comment by sdnasldksl** [comment]
> [#563 （评论）](https://github.com/seatonjiang/kratos/issues/563#issuecomment-1382632583)
是这个设置吗，请问它具体是在主体设置的哪个栏目

**Comment by sdnasldksl** [comment]
> [#563 （评论）](https://github.com/seatonjiang/kratos/issues/563#issuecomment-1382632583)

是我上面发的那个吗，不好意思第一次用这个不太会用

**Comment by n0099** [comment]
然后去`/wp-admin/widgets.php`里分别设置特定于3种页面（也就是他说的`侧边栏分 主页、文章、页面 三类，需要分别设置`）的小工具栏的小工具们

**Comment by sdnasldksl** [comment]
> 然后去`/wp-admin/widgets.php`里分别设置特定于3种页面（也就是他说的`侧边栏分 主页、文章、页面 三类，需要分别设置`）的小工具栏的小工具们

好的谢谢

**Comment by sdnasldksl** [comment]
> 然后去`/wp-admin/widgets.php`里分别设置特定于3种页面（也就是他说的`侧边栏分 主页、文章、页面 三类，需要分别设置`）的小工具栏的小工具们

请问这个文件夹哪个目录下面我没找到这个文件夹

**Comment by sdnasldksl** [comment]
> 然后去`/wp-admin/widgets.php`里分别设置特定于3种页面（也就是他说的`侧边栏分 主页、文章、页面 三类，需要分别设置`）的小工具栏的小工具们

刚刚在自己主机上找没找到，到服务器上找到了，感谢

**Comment by n0099** [comment]
`http(s)://your.domain/path/to/wp/wp-admin/widgets.php`

**Comment by seatonjiang** [comment]
问题已经长时间没有回复，暂时先关闭，仍有疑问可以随时打开反馈。
