### ISSUE TITLE
 预览文章和草稿内容不一致

### ISSUE THREAD

**Issue by iam386** [xb2016/Kratos#577]
网络正常的情况下，在草稿箱中更新了内容，但是打开预览的文章没有及时更新，这是系统问题吗？

**Comment by n0099** [comment]
您用了wpsupercache一类的静态缓存插件吗

**Comment by iam386** [comment]
没有呢，我以前用的主题没有问题，昨天切换过来就不行了。只安装了四个插件，激活的2个，我今天看了一下，还是不行，是什么原因呢？
![WordPress](https://user-images.githubusercontent.com/81946999/225170746-edd308d6-30c6-4090-9cc7-4e2d5d5e1611.png)

**Comment by n0099** [comment]
文章页url末尾有`?preview=true`吗

**Comment by iam386** [comment]
我点击更新，然后查看文章，url末尾没有?preview=true这个，就是显示文章的标题。

**Comment by iam386** [comment]
打开的文章是wp-admin/post.php?post=3124&action=edit这样的，查看的时候末尾是文章标题来着

**Comment by iam386** [comment]
我打开和关闭过Gutenberg 编辑器，文章发布的时候已关闭了Gutenberg编辑器，是这个原因导致的吗？

**Comment by n0099** [comment]
> 打开的文章是wp-admin/post.php?post=3124&action=edit这样的，查看的时候末尾是文章标题来着

那您就加上`?preview=true`之类的querystring以绕过wpsupercache一类的静态缓存（但您说您没有使用）

**Comment by iam386** [comment]
是的没有使用其它的插件，现在加上去试了，但是还是不行和发布好了的文章一样，缺少了很多内容，但是今天写的文章就不存在这个问题。

**Comment by iam386** [comment]
![Capture](https://user-images.githubusercontent.com/81946999/225186463-b73b13dd-aab8-4314-b931-212a9497364d.png)
![WordPres](https://user-images.githubusercontent.com/81946999/225186472-cbd3732e-a5e4-4bba-869d-50ad7910278e.png)
第一张是发布后的，第二张是没有发布的，发布后的少了对应的文字，就是这种情况。

**Comment by iam386** [comment]
找到原因了，应该是切换Gutenberg 编辑器产生了这种情况，使用文本的方式，可以看到后台没有，添加上这些问题就解决了

**Comment by n0099** [comment]
看看您的文章编辑页源代码视图（文字可以打码或替换成*，能看到html tag结构就行）

**Comment by iam386** [comment]
搞定了，就是切换编辑器的原因导致的，谢谢啦。
