### ISSUE TITLE
希望“收录配置”可以添加一个功能开关

### ISSUE THREAD

**Issue by simin-in-tw** [xb2016/Kratos#578]
在 Kratos 主题中，有个“收录配置”的菜单，希望可以像“Gravatar 加速服务”功能一样有个开关可以选择是否使用，避免与其他 SEO 插件重复生成关键词和站点描述的 meta 标签。

**Comment by n0099** [comment]
自己在[子主题](https://developer.wordpress.org/themes/advanced-topics/child-themes/)里修改`header.php`
https://github.com/seatonjiang/kratos/blob/0905b89f8789587ce550a3bebbb0e374f7f3a410/header.php#L19

**Comment by simin-in-tw** [comment]
研究了一下子主题，还是没搞懂，不过直接修改主题的文件也实现了。

**Comment by n0099** [comment]
然后下次更新主题您对主题的修改就失效了
另外根据[本repo所使用的GPL](https://github.com/seatonjiang/kratos/blob/main/LICENSE)，您必须开源您对主题的修改
