### ISSUE TITLE
能不能把个人简介的小工具的点击头像的链接变成自定义？

### ISSUE THREAD

**Issue by CoffeeHi** [xb2016/Kratos#583]
现在小工具里个人简介的头像会指向wp-login.php 页面，不太好，能取消或者改成自定义吗？

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/05b00b4f4b27a410ed996b0686dffa6bcdb79ac7/inc/theme-widgets.php#L307

**Comment by seatonjiang** [comment]
主题设置里有这个功能，关闭之后就不会点击跳后台了

![image](https://user-images.githubusercontent.com/57834639/228129192-5feb8a5e-aed2-4ada-a6ca-00a00f881334.png)
