### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [xb2016/Kratos#585]
Deleted

**Comment by kkksa528** [comment]
这是因为WordPress没引入这功能？

**Comment by seatonjiang** [comment]
把图片存到对象存储里就可以了，国内几家厂商的对象存储有你说的 WebP 压缩功能

**Comment by n0099** [comment]
一个主要目的是控制前端用户能看到的html/js/css内容的wp主题为什么要做这种早已被各路`图片处理管道aaS`厂商制作的wp插件集成（我知道的都有smush imagify shortpixel optimole： https://www.codeinwp.com/blog/imagify-vs-wp-smush-vs-shortpixel/ ，请注意我并不想给他们打广告也不推荐阁下购买他们的服务，除非阁下实在懒得手写处理管道）卷麻了的功能？经典之老wp主题膨胀到最后重复实现了许多单一用途wp插件中的方形轮子，最终由于[软件腐化](https://en.wikipedia.org/wiki/Software_rot)主题用户不得不换回单一用途的插件或自行fork/子主题修改逻辑


> 这是因为WordPress没引入这功能？

wp媒体库同样不会自带一个图片处理管道的功能，所以wp5.8+能做的不过就是默认给您在[`mime_types` filter](https://developer.wordpress.org/reference/hooks/mime_types/)中加入`image/webp` mime type，以及一些其他的：https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/
https://wordpress.stackexchange.com/questions/323221/allowing-webp-uploads
https://stackoverflow.com/questions/53427169/how-to-upload-webp-image-in-wordpress?noredirect=1&lq=1

同样没有什么能够阻止阁下自行写一堆[bash](https://mywiki.wooledge.org/BashPitfalls)来基于[inotifywait](https://linux.die.net/man/1/inotifywait) [cwebp](https://developers.google.com/speed/webp/docs/cwebp) [avifenc](https://github.com/AOMediaCodec/libavif)实现一个自带转换媒体库新上传图片为webp/avif/适合[文章列表页大小缩略图](https://github.com/seatonjiang/kratos/blob/89baae6198f4d85aec89e4c7601cd05edf78ca3e/inc/theme-article.php#LL116C10-L116C24)的图片处理管道

**Comment by n0099** [comment]
> 功能有点花里胡哨（原图保存，生成webp格式，自适应分发，接入CDN）

毕竟他们早就卷到麻木了，而且大部分图片处理管道aaS都是把您上传到媒体库的图片发给他们的服务端去处理，而不是在您的服务端上走管道，甚至最后前端请求的图片都还是在他们那（也就是所谓的CDN）
另外自适应分发的正式称呼是[内容协商](https://en.wikipedia.org/wiki/Content_negotiation)，主要是两种实现：
- 在前端看到的html中用[`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)让浏览器决定用哪张图片变种（也就是[feature detection](https://en.wikipedia.org/wiki/Feature_detection_(web_development))）从而实现[渐进升级](https://en.wikipedia.org/wiki/Progressive_enhancement) [优雅降级](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement)
- 在服务端通过UA header内容来猜测前端浏览器（如果他真的是浏览器而不是乱填UA的bot）支持什么（也就是[UA detection](https://en.wikipedia.org/wiki/User_agent#User_agent_sniffing)）并serve特定的图片变种


> 无损webp格式

然而lossless webp的压缩率不比最常见的png（在无损存储的基础上deflate一次）好多少，如果阁下真的要保证质量又要降低大小我建议直接快进到avif
https://developers.google.com/speed/webp/gallery2
https://www.ctrl.blog/entry/webp-flif-comparison.html
https://www.ctrl.blog/entry/webp-avif-comparison.html

我个人使用的有损webp和avif参数是
- `cwebp -m 6 -q 80 -sharp_yuv`
- `avifenc --min 0 --max 63 -s 0 -y 444 -j all --autotiling -a cq-level=25 -a end-usage=q -a tune=ssim -a aq-mode=1 -a enable-chroma-deltaq=1`

土澳文科生应用统计学带手子 @ControlNet 使用这两套参数对数千张二次元风格测试用例图片生成的webp和avif图片数据集的大小（因此如果阁下更在乎大小而不是更贴近原图那可以继续调参增加`cq-level`）和针对每对图片（`原图-webp`，`原图-avif`）计算出的[DSSIM](https://github.com/kornelski/dssim)是相似的，但`原图集-avif集`的[fid](https://github.com/mseitzer/pytorch-fid)比`原图集-webp集`的fid更接近原图： https://t.me/n0099_tg/118083

另外使用lossly有损webp时记得开启`-sharp_yuv`https://www.ctrl.blog/entry/webp-sharp-yuv.html
以及建议从 https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html 下载最新版本的libwebp，而不是像imagemagick那样还在静态编译远古版本的libwebp

最后对于本主题而言，针对[文章列表页](https://github.com/seatonjiang/kratos/blob/89baae6198f4d85aec89e4c7601cd05edf78ca3e/pages/page-content.php#L20)专门制作[文章特色图片](https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/)的缩略图（resize为适合放进`<img>`所在css box大小的分辨率）版本才是最有效的节省流量方式，因为几乎没有人类会把您站的每一篇文章都点出来看从而复用此前在文章列表页已经加载了的文章特色图片（前提是阁下也针对这些图片在http response header中设置了合适的[Cache-Control](https://csswizardry.com/2019/03/cache-control-for-civilians/) header从而让浏览器缓存他们）

**Comment by kkksa528** [comment]
> > 功能有点花里胡哨（原图保存，生成webp格式，自适应分发，接入CDN）
> 
> 毕竟他们早就卷到麻木了，而且大部分图片处理管道aaS都是把您上传到媒体库的图片发给他们的服务端去处理，而不是在您的服务端上走管道，甚至最后前端请求的图片都还是在他们那（也就是所谓的CDN） 另外自适应分发的正式称呼是[内容协商](https://en.wikipedia.org/wiki/Content_negotiation)，主要是两种实现：
> 
> * 在前端看到的html中用[`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)让浏览器决定用哪张图片变种（也就是[feature detection](https://en.wikipedia.org/wiki/Feature_detection_(web_development))）从而实现[渐进升级](https://en.wikipedia.org/wiki/Progressive_enhancement) [优雅降级](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement)
> * 在服务端通过UA header内容来猜测前端浏览器（如果他真的是浏览器而不是乱填UA的bot）支持什么（也就是[UA detection](https://en.wikipedia.org/wiki/User_agent#User_agent_sniffing)）并serve特定的图片变种
> 
> > 无损webp格式
> 
> 然而lossless webp的压缩率不比最常见的png（在无损存储的基础上deflate一次）好多少，如果阁下真的要保证质量又要降低大小我建议直接快进到avif https://developers.google.com/speed/webp/gallery2 https://www.ctrl.blog/entry/webp-flif-comparison.html https://www.ctrl.blog/entry/webp-avif-comparison.html
> 
> 我个人使用的有损webp和avif参数是
> 
> * `cwebp -m 6 -q 80 -sharp_yuv`
> * `avifenc --min 0 --max 63 -s 0 -y 444 -j all --autotiling -a cq-level=25 -a end-usage=q -a tune=ssim -a aq-mode=1 -a enable-chroma-deltaq=1`
> 
> 土澳文科生应用统计学带手子 @ControlNet 使用这两套参数对数千张二次元风格测试用例图片生成的webp和avif图片数据集的大小（因此如果阁下更在乎大小而不是更贴近原图那可以继续调参增加`cq-level`）和针对每对图片（`原图-webp`，`原图-avif`）计算出的[DSSIM](https://github.com/kornelski/dssim)是相似的，但`原图集-avif集`的[fid](https://github.com/mseitzer/pytorch-fid)比`原图集-webp集`的fid更接近原图： https://t.me/n0099_tg/118083
> 
> 另外使用lossly有损webp时记得开启`-sharp_yuv`https://www.ctrl.blog/entry/webp-sharp-yuv.html 以及建议从 https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html 下载最新版本的libwebp，而不是像imagemagick那样还在静态编译远古版本的libwebp
> 
> 最后对于本主题而言，针对[文章列表页](https://github.com/seatonjiang/kratos/blob/89baae6198f4d85aec89e4c7601cd05edf78ca3e/pages/page-content.php#L20)专门制作[文章特色图片](https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/)的缩略图（resize为适合放进`<img>`所在css box大小的分辨率）版本才是最有效的节省流量方式，因为几乎没有人类会把您站的每一篇文章都点出来看从而复用此前在文章列表页已经加载了的文章特色图片（前提是阁下也针对这些图片在http response header中设置了合适的[Cache-Control](https://csswizardry.com/2019/03/cache-control-for-civilians/) header从而让浏览器缓存他们）

好东西，学到了

**Comment by n0099** [comment]
经典之扣了一堆字结果读者只想TL;DR

**Comment by ControlNet** [comment]
快进到用chatgpt生成tldr

**Comment by huluohu** [comment]
自己整个图床呗（例如lsky），配合cf免费cdn，图片处理和存储没必要绑在wp上。
