### ISSUE TITLE
安装主题后移动端似乎难以正常访问

### ISSUE THREAD

**Issue by NyankoSong** [xb2016/Kratos#586]
你好！
我在一台无法连接互联网的内网机器上应用了本主题，在PC端可以正常访问使用。但是使用Android设备访问时会加载速度奇慢，可以长达数分钟。且除了WordPress原生主题的部分（例如顶部导航栏、登录页面等）之外的样式均无法正常加载，只剩下最基本的文字。
我根据之前的issue禁用了其中的所有加速服务，并没有改善这一情况。
希望能得到帮助，谢谢。

编辑：
我编辑完issue出去又看了一眼，访问速度莫名其妙的正常了，可我什么操作都没有做。。

**Comment by n0099** [comment]
f12-network按domain排序

**Comment by seatonjiang** [comment]
你今天发这个问题，多少有点玄学在里面

**Comment by NyankoSong** [comment]
> f12-network按domain排序

感谢回复！

不好意思，我找了半天没找见domain是哪个，按照名称排序了，而且我PC上访问正常，不知道能不能看出问题。。现在移动端上是能正常访问除了主题设置页面的其他页面（之前是只能访问默认主题的页面或内容），只要点主题设置就又会加载不进去。。

以下是关于主题设置这个页面的Network栏记录：

![屏幕截图 2023-04-06 180919](https://user-images.githubusercontent.com/50799323/230347701-0c6cfa43-3d34-4c01-83ee-ed737c54a33a.png)
![屏幕截图 2023-04-06 181039](https://user-images.githubusercontent.com/50799323/230347724-6f8186c2-775a-4072-882a-c956e53f228a.png)

> 你今天发这个问题，多少有点玄学在里面

唉。。

**Comment by n0099** [comment]
> 不好意思，我找了半天没找见domain是哪个，按照名称排序了，而且我PC上访问正常，不知道能不能看出问题。。现在移动端上是能正常访问除了主题设置页面的其他页面（之前是只能访问默认主题的页面或内容），只要点主题设置就又会加载不进去。。

不要机翻f12，请调回英文您就知道domain是哪个了
右键表格列名的菜单中可以启用显示domain列
另外您应该开启disable cache复选框
您在手机上用的是chrome吗？可以用chrome的usb调试来在pc上使用f12查看手机chrome的状况： https://developer.chrome.com/docs/devtools/remote-debugging/
另外我局的阁下大概率是被加载 https://gravatar.com 头像阻塞了，毕竟这个难以本地缓存又能始终保持同步（除非您保证所有人都不去gravatar更换头像）

**Comment by NyankoSong** [comment]
> > 不好意思，我找了半天没找见domain是哪个，按照名称排序了，而且我PC上访问正常，不知道能不能看出问题。。现在移动端上是能正常访问除了主题设置页面的其他页面（之前是只能访问默认主题的页面或内容），只要点主题设置就又会加载不进去。。
> 
> 不要机翻f12，请调回英文您就知道domain是哪个了 右键表格列名的菜单中可以启用显示domain列 另外您应该开启disable cache复选框 您在手机上用的是chrome吗？可以用chrome的usb调试来在pc上使用f12查看手机chrome的状况： https://developer.chrome.com/docs/devtools/remote-debugging/ 另外我局的阁下大概率是被加载 https://gravatar.com 头像阻塞了，毕竟这个难以本地缓存又能始终保持同步（除非您保证所有人都不去gravatar更换头像）

感谢指引，我大概弄明白怎么操作了。图有些多，我只把红色报错的部分放上来：

- 以下是PC部分，使用Edge浏览器访问

![屏幕截图 2023-04-06 212027](https://user-images.githubusercontent.com/50799323/230396184-15946084-d2cb-4daa-8f69-c582a7c42216.png)

- 以下是Android设备部分，使用Chrome浏览器访问

![屏幕截图 2023-04-06 213856](https://user-images.githubusercontent.com/50799323/230396357-ad76f861-49d8-4f9d-aa10-b67097ac37c7.png)

看起来可能是CDN的问题？可是我早已禁用了主题的静态资源加速服务。

**Comment by n0099** [comment]
是本主题所使用的依赖 https://github.com/Codestar/codestar-framework （用于主题设置页）加载的资源
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/code_editor/code_editor.php#L54
可以修改url前缀部分（合理假设阁下应该知道如何修改一个public class的public member之field的value）
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/code_editor/code_editor.php#L17
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/map/map.php#L17

但这里还有几处硬编码的：
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L569-L574
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L646
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L657
可以试试用[子主题](https://developer.wordpress.org/themes/advanced-topics/child-themes/)来修改
或是直接修改这些文件中的url（简单粗暴，但每次更新主题后都得手动再改一遍，建议github fork本主题并定期merge upstream以自动化）

https://github.com/seatonjiang/kratos/issues/578#issuecomment-1482961209 对此早有预言：
> 然后下次更新主题您对主题的修改就失效了 另外根据[本repo所使用的GPL](https://github.com/seatonjiang/kratos/blob/main/LICENSE?rgh-link-date=2023-03-24T15%3A09%3A17Z)，您必须开源您对主题的修改

**Comment by NyankoSong** [comment]
> 是本主题所使用的依赖 https://github.com/Codestar/codestar-framework （用于主题设置页）加载的资源
> 
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/code_editor/code_editor.php#L54
> 
> 
> 可以修改url前缀部分（合理假设阁下应该知道如何修改一个public class的public member之field的value）
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/code_editor/code_editor.php#L17
> 
> 
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/fields/map/map.php#L17
> 
> 但这里还有几处硬编码的：
> 
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L569-L574
> 
> 
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L646
> 
> 
> https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/codestar-framework/classes/setup.class.php#L657
> 
> 
> 可以试试用[子主题](https://developer.wordpress.org/themes/advanced-topics/child-themes/)来修改
> 或是直接修改这些文件中的url（简单粗暴，但每次更新主题后都得手动再改一遍，建议github fork本主题并定期merge upstream以自动化）
> [#578 (comment)](https://github.com/seatonjiang/kratos/issues/578#issuecomment-1482961209) 对此早有预言：
> 
> > 然后下次更新主题您对主题的修改就失效了 另外根据[本repo所使用的GPL](https://github.com/seatonjiang/kratos/blob/main/LICENSE?rgh-link-date=2023-03-24T15%3A09%3A17Z)，您必须开源您对主题的修改

感谢如此详尽的回答，但是由于我个人并没有接触过这方面的知识，故可能并不太能看懂您所提及的这些。。

我尝试性地更换了一些cdn，例如unpkg.com，但似乎都不太完全奏效。。

我之前提及本主题只会在内网使用，但其实服务器主机有纯IPv6网络，只是我下意识忽略了这件事。方才我也测试这个cdn似乎也可以通过IPv6访问。而我用PC访问时，我的PC其实也都有IPv6网络，但Android设备没有。尽管我是通过IPv4访问的网页？

不过由于折腾成本太高，我还是决定先凑合用了。。

另外是希望贵主题未来能提供纯离线使用的可能，谢谢。

**Comment by n0099** [comment]
> 更换了一些cdn，例如unpkg.com

如果阁下真的在完全无法访问公网的内网环境中那您换什么都没用，除非您内网某处有dns劫持把请求url的域给serve了

> 只会在内网使用，但其实服务器主机有纯IPv6网络

所以阁下只是没有公网ipv4访问，但有公网ipv6访问

> 我是通过IPv4访问的网页

您只是通过ipv4的`192.168.235.58`（您的截图中）访问了您所部署的wordpress，这跟 https://cdn.jsdelivr.net 解析为ipv4还是v6地址又有任何关系吗？

> 提供纯离线使用

您只需要把这些文件按url都下下来（[`wget`](https://www.gnu.org/software/wget/)）然后放在某处使得通过您的内网ip/域能够正常访问，然后再去修改上述文件中的url前缀字符串使其对应就行了

**Comment by NyankoSong** [comment]
> > 更换了一些cdn，例如unpkg.com
> 
> 如果阁下真的在完全无法访问公网的内网环境中那您换什么都没用，除非您内网某处有dns劫持把请求url的域给serve了
> 
> > 只会在内网使用，但其实服务器主机有纯IPv6网络
> 
> 所以阁下只是没有公网ipv4访问，但有公网ipv6访问
> 
> > 我是通过IPv4访问的网页
> 
> 您只是通过ipv4的`192.168.235.58`（您的截图中）访问了您所部署的wordpress，这跟 https://cdn.jsdelivr.net 解析为ipv4还是v6地址又有任何关系吗？
> 
> > 提供纯离线使用
> 
> 您只需要把这些文件按url都下下来（[`wget`](https://www.gnu.org/software/wget/)）然后放在某处使得通过您的内网ip/域能够正常访问，然后再去修改上述文件中的url前缀字符串使其对应就行了

感谢回复，我想我大概明白了。

我提到那些IP和访问是因为我之前以为是浏览器要从WordPress服务器间接地获取这些内容。而且我这边环境比较奇怪，客户端能访问公网，但服务器只有IPv6，所以我就提了一下这件事。

之前我提到“更换CDN不太能完全奏效”的意思，其实还是稍微奏效了一点。我现在明白过来了，这个CDN的IPv4因为某些可能的原因在我这边暂时无法正常访问，也许是我的PC端走了代理，也许是走了IPv6，导致最后体现出这样的差异。但是我更换了部分CDN之后，起码有些资源能正常访问了。

最后我提到希望提供纯离线使用，只是看有一个禁用静态资源加速，猜想也许这个也能像那样一样，可以在不用直面代码的情况下更换资源什么的。

总之，感谢您的耐心回复！

**Comment by seatonjiang** [comment]
codestar-framework 里面需要的资源在这里替换即可 https://www.staticfile.org/
