### ISSUE TITLE
怎么修改菜单的位置

### ISSUE THREAD

**Issue by chansonsky** [xb2016/Kratos#587]
如何能把右上角的菜单移到左边呢？又或者放在页眉的中间位置。

**Comment by n0099** [comment]
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/header.php#L77-L86
https://developer.wordpress.org/reference/functions/wp_nav_menu/
https://github.com/seatonjiang/kratos/blob/b6fc9457e7c915e64fffae387823e6fdec707862/inc/theme-navwalker.php#L41
https://github.com/wp-bootstrap/wp-bootstrap-navwalker
