### ISSUE TITLE
应用主题后有一些格式错乱

### ISSUE THREAD

**Issue by Shennng** [xb2016/Kratos#588]
我在WordPress里面安装了WPJAM插件，后面又禁用了该插件，依然出现了下面的问题，自己又看不懂php的代码，望指点迷津。

- 问题1：如下图，菜单栏和侧边栏都没有展示出来。
![uTools_1681797896423](https://user-images.githubusercontent.com/39769408/232686274-69681c64-3338-44cb-b46f-f19bf2a60660.png)

- 问题2：如下图，评论栏的emoji表情显示出错。
![uTools_1681797920175](https://user-images.githubusercontent.com/39769408/232686307-1a3a2fc8-eee0-4e2e-8bd4-64ca83a39ffe.png)

**Comment by seatonjiang** [comment]
网址发一下，然后贴一下关于主题里面的基础信息

**Comment by Shennng** [comment]
www.mibear.top

**Comment by seatonjiang** [comment]
这个地址没有解析啊

![image](https://user-images.githubusercontent.com/57834639/232690326-a1b3ee5d-5e67-43a0-a966-ec49ff6372f6.png)

**Comment by Shennng** [comment]
> 这个地址没有解析啊
> 
> ![image](https://user-images.githubusercontent.com/57834639/232690326-a1b3ee5d-5e67-43a0-a966-ec49ff6372f6.png)

mibear.top
我搞错了，抱歉

**Comment by Shennng** [comment]
发生错误的站点：mibear.top

**Comment by seatonjiang** [comment]
方便把网站管理员信息发一下吗，我登录看一下这篇文章，我的邮箱是 hi@seatonjiang.com

**Comment by Shennng** [comment]
> 方便把网站管理员信息发一下吗，我登录看一下这篇文章，我的邮箱是 [hi@seatonjiang.com](mailto:hi@seatonjiang.com)

已发

**Comment by Shennng** [comment]
我自己上午看了下，是我在应用kratos主题前写的文章下面评论区格式会乱掉，应用主题之后新增的文章就正常了。
至于导航栏没有显示的问题，是我没添加菜单（/笑哭），刚了解WordPress，完全不懂。
