### ISSUE TITLE
开启dogecloud云存储后媒体库不能正常显示

### ISSUE THREAD

**Issue by HugoWang232608** [xb2016/Kratos#589]
如题，在主题设置里开启dogecloud后，媒体库的图片无法正常显示，特色图片的缩略图无法显示，但是文章里的图片显示正常，不清楚是什么原因。图片url也发生了改变，https头不见了

**Comment by seatonjiang** [comment]
后台设置的时候「加速域名」要填写协议头

**Comment by qinbing8** [comment]
按照 Dogecloud 云存储官方配置加速域名后，不需要在主题设置开启 Dogecloud 云存储。

> 如题，在主题设置里开启dogecloud后，媒体库的图片无法正常显示，特色图片的缩略图无法显示，但是文章里的图片显示正常，不清楚是什么原因。图片url也发生了改变，https头不见了

**Comment by seatonjiang** [comment]
你好，这个问题解决了吗？暂时先把这个问题关闭了，如果还有问题请继续回复即可。
