### ISSUE TITLE
https://cdn.jsdelivr.net挂了，请火速更新

### ISSUE THREAD

**Issue by SoMeTech** [xb2016/Kratos#593]
https://cdn.jsdelivr.net挂了，请火速更新
css、js文件找不到了。界面是乱的

**Comment by seatonjiang** [comment]
关闭静态资源加速功能，jsDelivr大概率不会挂，你那边被墙是可能的

**Comment by fengjun8** [comment]
我这边也是这个连接被墙了，请问怎么更换为本地连接，现在禁用静态资源加速后前台没影响，但是后台打开主题进行设置时很慢
