### ISSUE TITLE
不能调节字体颜色

### ISSUE THREAD

**Issue by iam386** [xb2016/Kratos#595]
大佬，新升级的最新版本不能调节字体颜色。

**Comment by seatonjiang** [comment]
是编辑文章的时候改字体颜色，前台不生效吗？

**Comment by iam386** [comment]
对哒，没有那个功能了

**Comment by seatonjiang** [comment]
工具栏里面有个隐藏按钮，你点一下就出现了
![image](https://github.com/seatonjiang/kratos/assets/57834639/bd64ccf7-94a8-4b6e-89f6-51657f7fcb4c)

**Comment by iam386** [comment]
好的，谢谢，我的错
