### ISSUE TITLE
开启图片灯箱，但是没有效果

### ISSUE THREAD

**Issue by fengjun8** [xb2016/Kratos#596]
开启图片灯箱，但是没有效果，请问一般是啥问题？

**Comment by seatonjiang** [comment]
![image](https://github.com/seatonjiang/kratos/assets/57834639/8ca9a3dc-128e-48d6-9f28-8d219f0c416e)

添加图片时看一下上传的图片链接到是不是选择的「媒体文件」，如果选择的「无」就没效果，如果这里没问题的话，就浏览器debug看一下前端是不是有东西冲突报错了。

**Comment by seatonjiang** [comment]
问题解决了吗？暂时先关闭这个问题，再有问题，直接回复即可。
