### ISSUE TITLE
主题几个公用JS/CSS无法访问，怎么替换成本地的连接

### ISSUE THREAD

**Issue by Hbxycch** [xb2016/Kratos#598]
PHP 版本：7.4.0
Kratos 版本：4.2.2
WordPress 版本：6.1.3
几个公用JS、CSS报错无法访问，请问怎么替换成本地的
https://cdn.jsdelivr.net/gh/seatonjiang/kratos@v4.2.2/assets/js/bootstrap.bundle.min.js?ver=4.5.0

**Comment by seatonjiang** [comment]
把这个功能禁用就可以了

![image](https://github.com/seatonjiang/kratos/assets/57834639/556d29c3-2965-4f6a-81fb-04d2d96ec7fe)

**Comment by fengjun8** [comment]
已经禁用了，但是后台打开主题设置页面很慢，经检查还是jsdelivr的cdn无法访问导致的

**Comment by Hbxycch** [comment]
谢谢，关闭加速后，暂时没啥问题

**Comment by seatonjiang** [comment]
@fengjun8 更新一下最新版本，修复了后台jsdelivr的问题
