### ISSUE TITLE
最新版本的顶部下拉菜单不工作了

### ISSUE THREAD

**Issue by myf5** [xb2016/Kratos#599]
https://myf5.net可以看这个顶部的导航菜单，下拉菜单都不工作了。
注意到浮现类的功能都不工作了，比如浮现的二维码，点赞打赏的点击都不浮现了。
看了下网页的所有资源链接都是200 ok状态，没有什么js没下载。

**Comment by seatonjiang** [comment]
找一下这里是哪添加的

![image](https://github.com/seatonjiang/kratos/assets/57834639/80e9ff3d-36d8-4e62-b28d-dabef067ab6c)

**Comment by myf5** [comment]
fixed thanks.
