### ISSUE TITLE
建议令页面文件支持灯箱效果

### ISSUE THREAD

**Issue by Reius** [xb2016/Kratos#600]
文章页（single.php）已经支持了灯箱效果，但页面文件（page.php、page-full.php）中还没支持。建议支持。

**Comment by seatonjiang** [comment]
这个功能已经实现了，文章和页面单独控制，更新新版本即可。

![image](https://github.com/seatonjiang/kratos/assets/57834639/d7516d9d-70ec-4301-8f44-6b9e185cf7da)
