### ISSUE TITLE
kratos主题和fancybox 图片显示插件有冲突

### ISSUE THREAD

**Issue by bzhangmarvell** [xb2016/Kratos#602]
用了后文章内的图片点击后图片显示有两层， 上层是主题里的效果， 后面是fancybox 图片插件效果， 如何才能禁用主题的图片显示效果呢？

**Comment by bzhangmarvell** [comment]
找到原因了， 禁用文章图片灯箱就可以解决了

**Comment by seatonjiang** [comment]
@bzhangmarvell 是的，因为可能会有冲突问题，灯箱设置了一个开关，这样就可以解决了。
