### ISSUE TITLE
请问文章底部的评论如何移除？

### ISSUE THREAD

**Issue by kkwow** [xb2016/Kratos#605]
![Snipaste_2024-01-14_22-31-25](https://github.com/seatonjiang/kratos/assets/15723157/441a0c92-a4b7-49f4-981b-f240eaf4b8ad)

想移除红色区域的 个人资料+评论

请问该如何操作？ 后台设置没有找到呢。

**Comment by seatonjiang** [comment]
上面的作者介绍，可以把 pages/page-toolbar.php 文件的内容删除，文章评论在文章编辑里关掉就行了，效果如下图
<img width="1117" alt="image" src="https://github.com/seatonjiang/kratos/assets/57834639/50574834-04af-489a-97e2-07ef4f030917">

<img width="880" alt="image" src="https://github.com/seatonjiang/kratos/assets/57834639/472e97f5-30ef-484c-a823-bb03b87d1d3e">
