### ISSUE TITLE
发布文章页面无法填写

### ISSUE THREAD

**Issue by ghost** [xb2016/Kratos#615]
在应用主题后，发布文章页面无法填写，编辑区域变为白屏
![PixPin_2024-06-28_18-16-01](https://github.com/seatonjiang/kratos/assets/138630227/36e3d8a5-9f77-466e-b928-55670db40168)

**Comment by seatonjiang** [comment]
看一下是不是有插件冲突了，这个页面看起来是没有加载完成。

**Comment by ghost** [comment]
实锤了，要使用伪静态......
location /
{
	 try_files $uri $uri/ /index.php?$args;
}

rewrite /wp-admin$ $scheme://$host$uri/ permanent;

**Comment by LCXlichengxuan** [comment]
`d`
