### ISSUE TITLE
主题安装成功，但主页的分类导航栏没有出现

### ISSUE THREAD

**Issue by stuffren** [xb2016/Kratos#618]
我主题安装成功了，但主页右侧顶部看不到导航栏，将页面缩放到移动版本也看不到导航栏的菜单按钮
而我在后台提前新建过4个分类，以及新建过2个页面

wordpress版本：WordPress 6.6.1
浏览器及版本号：chorome 版本 127.0.6533.90（正式版本） （64 位）
kratos版本：v4.3.1

![01](https://github.com/user-attachments/assets/017fe72d-0778-405a-a46a-745f66bdf4ff)
主页截图
![02](https://github.com/user-attachments/assets/450b959e-e70e-426e-b7ad-c5105874c286)
分类设置截图
![03](https://github.com/user-attachments/assets/c8e34dae-1e98-4f25-a8d9-11195c3e6bbb)
页面设置截图

求作者帮忙解决，期待回复

**Comment by seatonjiang** [comment]
需要创建菜单（外观-菜单），显示位置选择顶部

**Comment by stuffren** [comment]
> 需要创建导航，添加到顶部

虽然你的回答并没有解决我的问题，但还是感谢你的回复。

**Comment by bc352562984** [comment]
同样的，无添加顶部菜单之后，不显示，添加一个项目之后直接显示项目然后再添加一个项目就又不显示了

**Comment by seatonjiang** [comment]
是这里勾选了之后，前端不显示吗？

![QQ_1731038895802](https://github.com/user-attachments/assets/24fc21aa-a43a-478e-8250-ed9065fb9fe2)
