### ISSUE TITLE
移动页面显示时，小工具（侧边栏）不可见

### ISSUE THREAD

**Issue by stuffren** [xb2016/Kratos#619]
当我把wordpress博客的首页通过chorme浏览器适配到移动页面的尺寸，页面会自动将导航收到弹出图标里（这是正常的），文章也会自动纵向排列（是正常的），但是右侧的侧边栏（即搜索，随机文章，标签等小工具）却不会自动移动到文章的下方，而是看不到了。

![01](https://github.com/user-attachments/assets/41bd37ef-c166-41df-ad70-1690c92169ee)

期待功能：
增加侧边栏（小工具）在移动端的显示

这个问题不只是我一个人有需求，我看到issues里也有其他的用户也提出了同样的需求，说明这是一个值得增加的功能！
等待作者的解决，感谢！

**Comment by iamlvtu** [comment]
删除主题目录下index.php文件第39行代码中
`d-none d-lg-block`
即可

**Comment by stuffren** [comment]
> 删除主题目录下index.php文件第39行代码中 `d-none d-lg-block` 即可

谢谢您的回复！问题已经解决了！ 感谢！！
