### ISSUE TITLE
后台设置框架不要使用 bootcdn 了

### ISSUE THREAD

**Issue by devhaozi** [xb2016/Kratos#621]
![图片](https://github.com/user-attachments/assets/d1cdbcd7-c380-4e20-90e4-f2e60fb4c30c)

如图，1 是很不稳定，经常各种加载不出来，2 是已经卖给灰产 Polyfill 了，有[篡改文件投毒历史](https://sansec.io/research/polyfill-supply-chain-attack)，像 Cloudlfare 和主流广告拦截规则都直接禁止加载相关域名的资源。
（国内几个公共 cdn 都被卖了，没被卖的也接近倒闭了，建议是直接下载外链的 js/css 放到主题里面或者用 jsdelivr 的子域名 fastly.jsdelivr.net，这个国内访问尚可，亦或者直接用 cdnjs 的 cdnjs.cloudflare.com，访问也很稳定）

![图片](https://github.com/user-attachments/assets/990f5c5d-6382-4f28-9fd6-79ee82de28e9)
![图片](https://github.com/user-attachments/assets/b5adcafd-93ba-424d-b709-83e6113d9d6c)

**Comment by nathan-L0** [comment]
感谢告知

**Comment by seatonjiang** [comment]
感谢反馈，jsdelivr 和 cloudflare 还是有不稳定的风险，最后换成了字节的库，CDN 是华为云的节点。

![QQ_1731038590829](https://github.com/user-attachments/assets/a7e1ef32-397e-40ed-851f-cfb565bd2006)

**Comment by devhaozi** [comment]
> 感谢反馈，jsdelivr 和 cloudflare 还是有不稳定的风险，最后换成了字节的库，CDN 是华为云的节点。
> 
> ![QQ_1731038590829](https://private-user-images.githubusercontent.com/57834639/384222519-a7e1ef32-397e-40ed-851f-cfb565bd2006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjAxNjMsIm5iZiI6MTczMTA1OTg2MywicGF0aCI6Ii81NzgzNDYzOS8zODQyMjI1MTktYTdlMWVmMzItMzk3ZS00MGVkLTg1MWYtY2ZiNTY1YmQyMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA5NTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMzNlZWMwOGM4YzkxM2EwMTBmM2U0OTJjMWU4ZjYzNTA0ZWJjZjk5MTQxZWY4MzUzNWJjMzc4YTQ1NDYwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LOYDcAMSynT2f7LsuHVpNJt26BXXnFsXlJZFKm1TDa4)

字节的倒是可以自选节点，看你想用什么：
```
//阿里云
lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M
//金山云
lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M
//白山云
lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M
//华为云
lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M
```

**Comment by yangyx91** [comment]
字节CDN也到期了【[](https://lf26-cdn-tos.bytecdntp.com/cdn/codemirror/)】。楼主下一个大版本，再切换下 自定义URL。谢谢
